/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StatisticByAgency service. Represents a row in the &quot;oep_dossiermgt_statisticbyagency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.dossiermgt.model.impl.StatisticByAgencyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.dossiermgt.model.impl.StatisticByAgencyImpl}.
 * </p>
 *
 * @author trungdk
 * @see StatisticByAgency
 * @see org.oep.dossiermgt.model.impl.StatisticByAgencyImpl
 * @see org.oep.dossiermgt.model.impl.StatisticByAgencyModelImpl
 * @generated
 */
public interface StatisticByAgencyModel extends BaseModel<StatisticByAgency> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a statistic by agency model instance should use the {@link StatisticByAgency} interface instead.
	 */

	/**
	 * Returns the primary key of this statistic by agency.
	 *
	 * @return the primary key of this statistic by agency
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this statistic by agency.
	 *
	 * @param primaryKey the primary key of this statistic by agency
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the statistic by agency ID of this statistic by agency.
	 *
	 * @return the statistic by agency ID of this statistic by agency
	 */
	public long getStatisticByAgencyId();

	/**
	 * Sets the statistic by agency ID of this statistic by agency.
	 *
	 * @param statisticByAgencyId the statistic by agency ID of this statistic by agency
	 */
	public void setStatisticByAgencyId(long statisticByAgencyId);

	/**
	 * Returns the group ID of this statistic by agency.
	 *
	 * @return the group ID of this statistic by agency
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this statistic by agency.
	 *
	 * @param groupId the group ID of this statistic by agency
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this statistic by agency.
	 *
	 * @return the company ID of this statistic by agency
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this statistic by agency.
	 *
	 * @param companyId the company ID of this statistic by agency
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this statistic by agency.
	 *
	 * @return the create date of this statistic by agency
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this statistic by agency.
	 *
	 * @param createDate the create date of this statistic by agency
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the month of this statistic by agency.
	 *
	 * @return the month of this statistic by agency
	 */
	public int getMonth();

	/**
	 * Sets the month of this statistic by agency.
	 *
	 * @param month the month of this statistic by agency
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this statistic by agency.
	 *
	 * @return the year of this statistic by agency
	 */
	public int getYear();

	/**
	 * Sets the year of this statistic by agency.
	 *
	 * @param year the year of this statistic by agency
	 */
	public void setYear(int year);

	/**
	 * Returns the gov agency ID of this statistic by agency.
	 *
	 * @return the gov agency ID of this statistic by agency
	 */
	@AutoEscape
	public String getGovAgencyId();

	/**
	 * Sets the gov agency ID of this statistic by agency.
	 *
	 * @param govAgencyId the gov agency ID of this statistic by agency
	 */
	public void setGovAgencyId(String govAgencyId);

	/**
	 * Returns the receive number of this statistic by agency.
	 *
	 * @return the receive number of this statistic by agency
	 */
	public long getReceiveNumber();

	/**
	 * Sets the receive number of this statistic by agency.
	 *
	 * @param receiveNumber the receive number of this statistic by agency
	 */
	public void setReceiveNumber(long receiveNumber);

	/**
	 * Returns the online number of this statistic by agency.
	 *
	 * @return the online number of this statistic by agency
	 */
	public long getOnlineNumber();

	/**
	 * Sets the online number of this statistic by agency.
	 *
	 * @param onlineNumber the online number of this statistic by agency
	 */
	public void setOnlineNumber(long onlineNumber);

	/**
	 * Returns the online ratio of this statistic by agency.
	 *
	 * @return the online ratio of this statistic by agency
	 */
	public double getOnlineRatio();

	/**
	 * Sets the online ratio of this statistic by agency.
	 *
	 * @param onlineRatio the online ratio of this statistic by agency
	 */
	public void setOnlineRatio(double onlineRatio);

	/**
	 * Returns the finish number of this statistic by agency.
	 *
	 * @return the finish number of this statistic by agency
	 */
	public int getFinishNumber();

	/**
	 * Sets the finish number of this statistic by agency.
	 *
	 * @param finishNumber the finish number of this statistic by agency
	 */
	public void setFinishNumber(int finishNumber);

	/**
	 * Returns the ontime number of this statistic by agency.
	 *
	 * @return the ontime number of this statistic by agency
	 */
	public int getOntimeNumber();

	/**
	 * Sets the ontime number of this statistic by agency.
	 *
	 * @param ontimeNumber the ontime number of this statistic by agency
	 */
	public void setOntimeNumber(int ontimeNumber);

	/**
	 * Returns the ontime ratio of this statistic by agency.
	 *
	 * @return the ontime ratio of this statistic by agency
	 */
	public double getOntimeRatio();

	/**
	 * Sets the ontime ratio of this statistic by agency.
	 *
	 * @param ontimeRatio the ontime ratio of this statistic by agency
	 */
	public void setOntimeRatio(double ontimeRatio);

	/**
	 * Returns the delay days avg of this statistic by agency.
	 *
	 * @return the delay days avg of this statistic by agency
	 */
	public double getDelayDaysAvg();

	/**
	 * Sets the delay days avg of this statistic by agency.
	 *
	 * @param delayDaysAvg the delay days avg of this statistic by agency
	 */
	public void setDelayDaysAvg(double delayDaysAvg);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StatisticByAgency statisticByAgency);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StatisticByAgency> toCacheModel();

	@Override
	public StatisticByAgency toEscapedModel();

	@Override
	public StatisticByAgency toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}