/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.dossiermgt.model.DossierProcBookmark;
import org.oep.core.dossiermgt.model.DossierProcBookmarkModel;
import org.oep.core.dossiermgt.model.DossierProcBookmarkSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DossierProcBookmark service. Represents a row in the &quot;oep_dossiermgt_dossierprocbookmark&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.dossiermgt.model.DossierProcBookmarkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DossierProcBookmarkImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierProcBookmarkImpl
 * @see org.oep.core.dossiermgt.model.DossierProcBookmark
 * @see org.oep.core.dossiermgt.model.DossierProcBookmarkModel
 * @generated
 */
@JSON(strict = true)
public class DossierProcBookmarkModelImpl extends BaseModelImpl<DossierProcBookmark>
	implements DossierProcBookmarkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dossier proc bookmark model instance should use the {@link org.oep.core.dossiermgt.model.DossierProcBookmark} interface instead.
	 */
	public static final String TABLE_NAME = "oep_dossiermgt_dossierprocbookmark";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dossierProcBookmarkId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "dossierProcAgentId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_dossiermgt_dossierprocbookmark (dossierProcBookmarkId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,createDate DATE null,dossierProcAgentId LONG)";
	public static final String TABLE_SQL_DROP = "drop table oep_dossiermgt_dossierprocbookmark";
	public static final String ORDER_BY_JPQL = " ORDER BY dossierProcBookmark.dossierProcBookmarkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_dossiermgt_dossierprocbookmark.dossierProcBookmarkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.dossiermgt.model.DossierProcBookmark"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.dossiermgt.model.DossierProcBookmark"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DossierProcBookmark toModel(DossierProcBookmarkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DossierProcBookmark model = new DossierProcBookmarkImpl();

		model.setDossierProcBookmarkId(soapModel.getDossierProcBookmarkId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setDossierProcAgentId(soapModel.getDossierProcAgentId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DossierProcBookmark> toModels(
		DossierProcBookmarkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DossierProcBookmark> models = new ArrayList<DossierProcBookmark>(soapModels.length);

		for (DossierProcBookmarkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.dossiermgt.model.DossierProcBookmark"));

	public DossierProcBookmarkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dossierProcBookmarkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDossierProcBookmarkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dossierProcBookmarkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DossierProcBookmark.class;
	}

	@Override
	public String getModelClassName() {
		return DossierProcBookmark.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dossierProcBookmarkId", getDossierProcBookmarkId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("dossierProcAgentId", getDossierProcAgentId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dossierProcBookmarkId = (Long)attributes.get(
				"dossierProcBookmarkId");

		if (dossierProcBookmarkId != null) {
			setDossierProcBookmarkId(dossierProcBookmarkId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long dossierProcAgentId = (Long)attributes.get("dossierProcAgentId");

		if (dossierProcAgentId != null) {
			setDossierProcAgentId(dossierProcAgentId);
		}
	}

	@JSON
	@Override
	public long getDossierProcBookmarkId() {
		return _dossierProcBookmarkId;
	}

	@Override
	public void setDossierProcBookmarkId(long dossierProcBookmarkId) {
		_dossierProcBookmarkId = dossierProcBookmarkId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public long getDossierProcAgentId() {
		return _dossierProcAgentId;
	}

	@Override
	public void setDossierProcAgentId(long dossierProcAgentId) {
		_dossierProcAgentId = dossierProcAgentId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DossierProcBookmark.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DossierProcBookmark toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DossierProcBookmark)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DossierProcBookmarkImpl dossierProcBookmarkImpl = new DossierProcBookmarkImpl();

		dossierProcBookmarkImpl.setDossierProcBookmarkId(getDossierProcBookmarkId());
		dossierProcBookmarkImpl.setUserId(getUserId());
		dossierProcBookmarkImpl.setGroupId(getGroupId());
		dossierProcBookmarkImpl.setCompanyId(getCompanyId());
		dossierProcBookmarkImpl.setCreateDate(getCreateDate());
		dossierProcBookmarkImpl.setDossierProcAgentId(getDossierProcAgentId());

		dossierProcBookmarkImpl.resetOriginalValues();

		return dossierProcBookmarkImpl;
	}

	@Override
	public int compareTo(DossierProcBookmark dossierProcBookmark) {
		long primaryKey = dossierProcBookmark.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DossierProcBookmark)) {
			return false;
		}

		DossierProcBookmark dossierProcBookmark = (DossierProcBookmark)obj;

		long primaryKey = dossierProcBookmark.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DossierProcBookmark> toCacheModel() {
		DossierProcBookmarkCacheModel dossierProcBookmarkCacheModel = new DossierProcBookmarkCacheModel();

		dossierProcBookmarkCacheModel.dossierProcBookmarkId = getDossierProcBookmarkId();

		dossierProcBookmarkCacheModel.userId = getUserId();

		dossierProcBookmarkCacheModel.groupId = getGroupId();

		dossierProcBookmarkCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			dossierProcBookmarkCacheModel.createDate = createDate.getTime();
		}
		else {
			dossierProcBookmarkCacheModel.createDate = Long.MIN_VALUE;
		}

		dossierProcBookmarkCacheModel.dossierProcAgentId = getDossierProcAgentId();

		return dossierProcBookmarkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{dossierProcBookmarkId=");
		sb.append(getDossierProcBookmarkId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", dossierProcAgentId=");
		sb.append(getDossierProcAgentId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.dossiermgt.model.DossierProcBookmark");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dossierProcBookmarkId</column-name><column-value><![CDATA[");
		sb.append(getDossierProcBookmarkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierProcAgentId</column-name><column-value><![CDATA[");
		sb.append(getDossierProcAgentId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DossierProcBookmark.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DossierProcBookmark.class
		};
	private long _dossierProcBookmarkId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _dossierProcAgentId;
	private DossierProcBookmark _escapedModel;
}