/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.dossiermgt.model.DossierProc2Agent;
import org.oep.core.dossiermgt.model.DossierProc2AgentModel;
import org.oep.core.dossiermgt.model.DossierProc2AgentSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DossierProc2Agent service. Represents a row in the &quot;oep_dossiermgt_DossierProc2Agent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.dossiermgt.model.DossierProc2AgentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DossierProc2AgentImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierProc2AgentImpl
 * @see org.oep.core.dossiermgt.model.DossierProc2Agent
 * @see org.oep.core.dossiermgt.model.DossierProc2AgentModel
 * @generated
 */
@JSON(strict = true)
public class DossierProc2AgentModelImpl extends BaseModelImpl<DossierProc2Agent>
	implements DossierProc2AgentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dossier proc2 agent model instance should use the {@link org.oep.core.dossiermgt.model.DossierProc2Agent} interface instead.
	 */
	public static final String TABLE_NAME = "oep_dossiermgt_DossierProc2Agent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "dossierProcId", Types.BIGINT },
			{ "govAgentNo", Types.VARCHAR },
			{ "govAgentName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_dossiermgt_DossierProc2Agent (id_ LONG not null primary key,companyId LONG,dossierProcId LONG,govAgentNo VARCHAR(75) null,govAgentName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table oep_dossiermgt_DossierProc2Agent";
	public static final String ORDER_BY_JPQL = " ORDER BY dossierProc2Agent.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_dossiermgt_DossierProc2Agent.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.dossiermgt.model.DossierProc2Agent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.dossiermgt.model.DossierProc2Agent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DossierProc2Agent toModel(DossierProc2AgentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DossierProc2Agent model = new DossierProc2AgentImpl();

		model.setId(soapModel.getId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setDossierProcId(soapModel.getDossierProcId());
		model.setGovAgentNo(soapModel.getGovAgentNo());
		model.setGovAgentName(soapModel.getGovAgentName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DossierProc2Agent> toModels(
		DossierProc2AgentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DossierProc2Agent> models = new ArrayList<DossierProc2Agent>(soapModels.length);

		for (DossierProc2AgentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.dossiermgt.model.DossierProc2Agent"));

	public DossierProc2AgentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DossierProc2Agent.class;
	}

	@Override
	public String getModelClassName() {
		return DossierProc2Agent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("companyId", getCompanyId());
		attributes.put("dossierProcId", getDossierProcId());
		attributes.put("govAgentNo", getGovAgentNo());
		attributes.put("govAgentName", getGovAgentName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long dossierProcId = (Long)attributes.get("dossierProcId");

		if (dossierProcId != null) {
			setDossierProcId(dossierProcId);
		}

		String govAgentNo = (String)attributes.get("govAgentNo");

		if (govAgentNo != null) {
			setGovAgentNo(govAgentNo);
		}

		String govAgentName = (String)attributes.get("govAgentName");

		if (govAgentName != null) {
			setGovAgentName(govAgentName);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getDossierProcId() {
		return _dossierProcId;
	}

	@Override
	public void setDossierProcId(long dossierProcId) {
		_dossierProcId = dossierProcId;
	}

	@JSON
	@Override
	public String getGovAgentNo() {
		if (_govAgentNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgentNo;
		}
	}

	@Override
	public void setGovAgentNo(String govAgentNo) {
		_govAgentNo = govAgentNo;
	}

	@JSON
	@Override
	public String getGovAgentName() {
		if (_govAgentName == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgentName;
		}
	}

	@Override
	public void setGovAgentName(String govAgentName) {
		_govAgentName = govAgentName;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DossierProc2Agent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DossierProc2Agent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DossierProc2Agent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DossierProc2AgentImpl dossierProc2AgentImpl = new DossierProc2AgentImpl();

		dossierProc2AgentImpl.setId(getId());
		dossierProc2AgentImpl.setCompanyId(getCompanyId());
		dossierProc2AgentImpl.setDossierProcId(getDossierProcId());
		dossierProc2AgentImpl.setGovAgentNo(getGovAgentNo());
		dossierProc2AgentImpl.setGovAgentName(getGovAgentName());

		dossierProc2AgentImpl.resetOriginalValues();

		return dossierProc2AgentImpl;
	}

	@Override
	public int compareTo(DossierProc2Agent dossierProc2Agent) {
		long primaryKey = dossierProc2Agent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DossierProc2Agent)) {
			return false;
		}

		DossierProc2Agent dossierProc2Agent = (DossierProc2Agent)obj;

		long primaryKey = dossierProc2Agent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DossierProc2Agent> toCacheModel() {
		DossierProc2AgentCacheModel dossierProc2AgentCacheModel = new DossierProc2AgentCacheModel();

		dossierProc2AgentCacheModel.id = getId();

		dossierProc2AgentCacheModel.companyId = getCompanyId();

		dossierProc2AgentCacheModel.dossierProcId = getDossierProcId();

		dossierProc2AgentCacheModel.govAgentNo = getGovAgentNo();

		String govAgentNo = dossierProc2AgentCacheModel.govAgentNo;

		if ((govAgentNo != null) && (govAgentNo.length() == 0)) {
			dossierProc2AgentCacheModel.govAgentNo = null;
		}

		dossierProc2AgentCacheModel.govAgentName = getGovAgentName();

		String govAgentName = dossierProc2AgentCacheModel.govAgentName;

		if ((govAgentName != null) && (govAgentName.length() == 0)) {
			dossierProc2AgentCacheModel.govAgentName = null;
		}

		return dossierProc2AgentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", dossierProcId=");
		sb.append(getDossierProcId());
		sb.append(", govAgentNo=");
		sb.append(getGovAgentNo());
		sb.append(", govAgentName=");
		sb.append(getGovAgentName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.dossiermgt.model.DossierProc2Agent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierProcId</column-name><column-value><![CDATA[");
		sb.append(getDossierProcId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgentNo</column-name><column-value><![CDATA[");
		sb.append(getGovAgentNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgentName</column-name><column-value><![CDATA[");
		sb.append(getGovAgentName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DossierProc2Agent.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DossierProc2Agent.class
		};
	private long _id;
	private long _companyId;
	private long _dossierProcId;
	private String _govAgentNo;
	private String _govAgentName;
	private DossierProc2Agent _escapedModel;
}