/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.oep.core.dossiermgt.model.DossierDoc2Template;
import org.oep.core.dossiermgt.model.DossierDoc2TemplateModel;
import org.oep.core.dossiermgt.model.DossierDoc2TemplateSoap;
import org.oep.core.dossiermgt.service.persistence.DossierDoc2TemplatePK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DossierDoc2Template service. Represents a row in the &quot;oep_dossiermgt_dossierdoc2template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.dossiermgt.model.DossierDoc2TemplateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DossierDoc2TemplateImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierDoc2TemplateImpl
 * @see org.oep.core.dossiermgt.model.DossierDoc2Template
 * @see org.oep.core.dossiermgt.model.DossierDoc2TemplateModel
 * @generated
 */
@JSON(strict = true)
public class DossierDoc2TemplateModelImpl extends BaseModelImpl<DossierDoc2Template>
	implements DossierDoc2TemplateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dossier doc2 template model instance should use the {@link org.oep.core.dossiermgt.model.DossierDoc2Template} interface instead.
	 */
	public static final String TABLE_NAME = "oep_dossiermgt_dossierdoc2template";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dossierDocId", Types.BIGINT },
			{ "docTemplateId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_dossiermgt_dossierdoc2template (dossierDocId LONG not null,docTemplateId LONG not null,primary key (dossierDocId, docTemplateId))";
	public static final String TABLE_SQL_DROP = "drop table oep_dossiermgt_dossierdoc2template";
	public static final String ORDER_BY_JPQL = " ORDER BY dossierDoc2Template.id.dossierDocId ASC, dossierDoc2Template.id.docTemplateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_dossiermgt_dossierdoc2template.dossierDocId ASC, oep_dossiermgt_dossierdoc2template.docTemplateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.dossiermgt.model.DossierDoc2Template"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.dossiermgt.model.DossierDoc2Template"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DossierDoc2Template toModel(DossierDoc2TemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DossierDoc2Template model = new DossierDoc2TemplateImpl();

		model.setDossierDocId(soapModel.getDossierDocId());
		model.setDocTemplateId(soapModel.getDocTemplateId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DossierDoc2Template> toModels(
		DossierDoc2TemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DossierDoc2Template> models = new ArrayList<DossierDoc2Template>(soapModels.length);

		for (DossierDoc2TemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.dossiermgt.model.DossierDoc2Template"));

	public DossierDoc2TemplateModelImpl() {
	}

	@Override
	public DossierDoc2TemplatePK getPrimaryKey() {
		return new DossierDoc2TemplatePK(_dossierDocId, _docTemplateId);
	}

	@Override
	public void setPrimaryKey(DossierDoc2TemplatePK primaryKey) {
		setDossierDocId(primaryKey.dossierDocId);
		setDocTemplateId(primaryKey.docTemplateId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new DossierDoc2TemplatePK(_dossierDocId, _docTemplateId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((DossierDoc2TemplatePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DossierDoc2Template.class;
	}

	@Override
	public String getModelClassName() {
		return DossierDoc2Template.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dossierDocId", getDossierDocId());
		attributes.put("docTemplateId", getDocTemplateId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dossierDocId = (Long)attributes.get("dossierDocId");

		if (dossierDocId != null) {
			setDossierDocId(dossierDocId);
		}

		Long docTemplateId = (Long)attributes.get("docTemplateId");

		if (docTemplateId != null) {
			setDocTemplateId(docTemplateId);
		}
	}

	@JSON
	@Override
	public long getDossierDocId() {
		return _dossierDocId;
	}

	@Override
	public void setDossierDocId(long dossierDocId) {
		_dossierDocId = dossierDocId;
	}

	@JSON
	@Override
	public long getDocTemplateId() {
		return _docTemplateId;
	}

	@Override
	public void setDocTemplateId(long docTemplateId) {
		_docTemplateId = docTemplateId;
	}

	@Override
	public DossierDoc2Template toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DossierDoc2Template)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DossierDoc2TemplateImpl dossierDoc2TemplateImpl = new DossierDoc2TemplateImpl();

		dossierDoc2TemplateImpl.setDossierDocId(getDossierDocId());
		dossierDoc2TemplateImpl.setDocTemplateId(getDocTemplateId());

		dossierDoc2TemplateImpl.resetOriginalValues();

		return dossierDoc2TemplateImpl;
	}

	@Override
	public int compareTo(DossierDoc2Template dossierDoc2Template) {
		DossierDoc2TemplatePK primaryKey = dossierDoc2Template.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DossierDoc2Template)) {
			return false;
		}

		DossierDoc2Template dossierDoc2Template = (DossierDoc2Template)obj;

		DossierDoc2TemplatePK primaryKey = dossierDoc2Template.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DossierDoc2Template> toCacheModel() {
		DossierDoc2TemplateCacheModel dossierDoc2TemplateCacheModel = new DossierDoc2TemplateCacheModel();

		dossierDoc2TemplateCacheModel.dossierDocId = getDossierDocId();

		dossierDoc2TemplateCacheModel.docTemplateId = getDocTemplateId();

		return dossierDoc2TemplateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{dossierDocId=");
		sb.append(getDossierDocId());
		sb.append(", docTemplateId=");
		sb.append(getDocTemplateId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.dossiermgt.model.DossierDoc2Template");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dossierDocId</column-name><column-value><![CDATA[");
		sb.append(getDossierDocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>docTemplateId</column-name><column-value><![CDATA[");
		sb.append(getDocTemplateId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DossierDoc2Template.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DossierDoc2Template.class
		};
	private long _dossierDocId;
	private long _docTemplateId;
	private DossierDoc2Template _escapedModel;
}