/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.dossiermgt.model.StatisticByAgency;
import org.oep.core.dossiermgt.model.StatisticByAgencyModel;
import org.oep.core.dossiermgt.model.StatisticByAgencySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatisticByAgency service. Represents a row in the &quot;oep_dossiermgt_statisticbyagency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.dossiermgt.model.StatisticByAgencyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatisticByAgencyImpl}.
 * </p>
 *
 * @author trungdk
 * @see StatisticByAgencyImpl
 * @see org.oep.core.dossiermgt.model.StatisticByAgency
 * @see org.oep.core.dossiermgt.model.StatisticByAgencyModel
 * @generated
 */
@JSON(strict = true)
public class StatisticByAgencyModelImpl extends BaseModelImpl<StatisticByAgency>
	implements StatisticByAgencyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a statistic by agency model instance should use the {@link org.oep.core.dossiermgt.model.StatisticByAgency} interface instead.
	 */
	public static final String TABLE_NAME = "oep_dossiermgt_statisticbyagency";
	public static final Object[][] TABLE_COLUMNS = {
			{ "statisticByAgencyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "month", Types.INTEGER },
			{ "year", Types.INTEGER },
			{ "govAgencyId", Types.VARCHAR },
			{ "receiveNumber", Types.BIGINT },
			{ "onlineNumber", Types.BIGINT },
			{ "onlineRatio", Types.DOUBLE },
			{ "finishNumber", Types.INTEGER },
			{ "ontimeNumber", Types.INTEGER },
			{ "ontimeRatio", Types.DOUBLE },
			{ "delayDaysAvg", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_dossiermgt_statisticbyagency (statisticByAgencyId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,month INTEGER,year INTEGER,govAgencyId VARCHAR(30) null,receiveNumber LONG,onlineNumber LONG,onlineRatio DOUBLE,finishNumber INTEGER,ontimeNumber INTEGER,ontimeRatio DOUBLE,delayDaysAvg DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table oep_dossiermgt_statisticbyagency";
	public static final String ORDER_BY_JPQL = " ORDER BY statisticByAgency.statisticByAgencyId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_dossiermgt_statisticbyagency.statisticByAgencyId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.dossiermgt.model.StatisticByAgency"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.dossiermgt.model.StatisticByAgency"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatisticByAgency toModel(StatisticByAgencySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatisticByAgency model = new StatisticByAgencyImpl();

		model.setStatisticByAgencyId(soapModel.getStatisticByAgencyId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setMonth(soapModel.getMonth());
		model.setYear(soapModel.getYear());
		model.setGovAgencyId(soapModel.getGovAgencyId());
		model.setReceiveNumber(soapModel.getReceiveNumber());
		model.setOnlineNumber(soapModel.getOnlineNumber());
		model.setOnlineRatio(soapModel.getOnlineRatio());
		model.setFinishNumber(soapModel.getFinishNumber());
		model.setOntimeNumber(soapModel.getOntimeNumber());
		model.setOntimeRatio(soapModel.getOntimeRatio());
		model.setDelayDaysAvg(soapModel.getDelayDaysAvg());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatisticByAgency> toModels(
		StatisticByAgencySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatisticByAgency> models = new ArrayList<StatisticByAgency>(soapModels.length);

		for (StatisticByAgencySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.dossiermgt.model.StatisticByAgency"));

	public StatisticByAgencyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _statisticByAgencyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStatisticByAgencyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _statisticByAgencyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatisticByAgency.class;
	}

	@Override
	public String getModelClassName() {
		return StatisticByAgency.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("statisticByAgencyId", getStatisticByAgencyId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("month", getMonth());
		attributes.put("year", getYear());
		attributes.put("govAgencyId", getGovAgencyId());
		attributes.put("receiveNumber", getReceiveNumber());
		attributes.put("onlineNumber", getOnlineNumber());
		attributes.put("onlineRatio", getOnlineRatio());
		attributes.put("finishNumber", getFinishNumber());
		attributes.put("ontimeNumber", getOntimeNumber());
		attributes.put("ontimeRatio", getOntimeRatio());
		attributes.put("delayDaysAvg", getDelayDaysAvg());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long statisticByAgencyId = (Long)attributes.get("statisticByAgencyId");

		if (statisticByAgencyId != null) {
			setStatisticByAgencyId(statisticByAgencyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Integer month = (Integer)attributes.get("month");

		if (month != null) {
			setMonth(month);
		}

		Integer year = (Integer)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		String govAgencyId = (String)attributes.get("govAgencyId");

		if (govAgencyId != null) {
			setGovAgencyId(govAgencyId);
		}

		Long receiveNumber = (Long)attributes.get("receiveNumber");

		if (receiveNumber != null) {
			setReceiveNumber(receiveNumber);
		}

		Long onlineNumber = (Long)attributes.get("onlineNumber");

		if (onlineNumber != null) {
			setOnlineNumber(onlineNumber);
		}

		Double onlineRatio = (Double)attributes.get("onlineRatio");

		if (onlineRatio != null) {
			setOnlineRatio(onlineRatio);
		}

		Integer finishNumber = (Integer)attributes.get("finishNumber");

		if (finishNumber != null) {
			setFinishNumber(finishNumber);
		}

		Integer ontimeNumber = (Integer)attributes.get("ontimeNumber");

		if (ontimeNumber != null) {
			setOntimeNumber(ontimeNumber);
		}

		Double ontimeRatio = (Double)attributes.get("ontimeRatio");

		if (ontimeRatio != null) {
			setOntimeRatio(ontimeRatio);
		}

		Double delayDaysAvg = (Double)attributes.get("delayDaysAvg");

		if (delayDaysAvg != null) {
			setDelayDaysAvg(delayDaysAvg);
		}
	}

	@JSON
	@Override
	public long getStatisticByAgencyId() {
		return _statisticByAgencyId;
	}

	@Override
	public void setStatisticByAgencyId(long statisticByAgencyId) {
		_statisticByAgencyId = statisticByAgencyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public int getMonth() {
		return _month;
	}

	@Override
	public void setMonth(int month) {
		_month = month;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		_year = year;
	}

	@JSON
	@Override
	public String getGovAgencyId() {
		if (_govAgencyId == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgencyId;
		}
	}

	@Override
	public void setGovAgencyId(String govAgencyId) {
		_govAgencyId = govAgencyId;
	}

	@JSON
	@Override
	public long getReceiveNumber() {
		return _receiveNumber;
	}

	@Override
	public void setReceiveNumber(long receiveNumber) {
		_receiveNumber = receiveNumber;
	}

	@JSON
	@Override
	public long getOnlineNumber() {
		return _onlineNumber;
	}

	@Override
	public void setOnlineNumber(long onlineNumber) {
		_onlineNumber = onlineNumber;
	}

	@JSON
	@Override
	public double getOnlineRatio() {
		return _onlineRatio;
	}

	@Override
	public void setOnlineRatio(double onlineRatio) {
		_onlineRatio = onlineRatio;
	}

	@JSON
	@Override
	public int getFinishNumber() {
		return _finishNumber;
	}

	@Override
	public void setFinishNumber(int finishNumber) {
		_finishNumber = finishNumber;
	}

	@JSON
	@Override
	public int getOntimeNumber() {
		return _ontimeNumber;
	}

	@Override
	public void setOntimeNumber(int ontimeNumber) {
		_ontimeNumber = ontimeNumber;
	}

	@JSON
	@Override
	public double getOntimeRatio() {
		return _ontimeRatio;
	}

	@Override
	public void setOntimeRatio(double ontimeRatio) {
		_ontimeRatio = ontimeRatio;
	}

	@JSON
	@Override
	public double getDelayDaysAvg() {
		return _delayDaysAvg;
	}

	@Override
	public void setDelayDaysAvg(double delayDaysAvg) {
		_delayDaysAvg = delayDaysAvg;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			StatisticByAgency.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatisticByAgency toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatisticByAgency)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatisticByAgencyImpl statisticByAgencyImpl = new StatisticByAgencyImpl();

		statisticByAgencyImpl.setStatisticByAgencyId(getStatisticByAgencyId());
		statisticByAgencyImpl.setGroupId(getGroupId());
		statisticByAgencyImpl.setCompanyId(getCompanyId());
		statisticByAgencyImpl.setCreateDate(getCreateDate());
		statisticByAgencyImpl.setMonth(getMonth());
		statisticByAgencyImpl.setYear(getYear());
		statisticByAgencyImpl.setGovAgencyId(getGovAgencyId());
		statisticByAgencyImpl.setReceiveNumber(getReceiveNumber());
		statisticByAgencyImpl.setOnlineNumber(getOnlineNumber());
		statisticByAgencyImpl.setOnlineRatio(getOnlineRatio());
		statisticByAgencyImpl.setFinishNumber(getFinishNumber());
		statisticByAgencyImpl.setOntimeNumber(getOntimeNumber());
		statisticByAgencyImpl.setOntimeRatio(getOntimeRatio());
		statisticByAgencyImpl.setDelayDaysAvg(getDelayDaysAvg());

		statisticByAgencyImpl.resetOriginalValues();

		return statisticByAgencyImpl;
	}

	@Override
	public int compareTo(StatisticByAgency statisticByAgency) {
		long primaryKey = statisticByAgency.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatisticByAgency)) {
			return false;
		}

		StatisticByAgency statisticByAgency = (StatisticByAgency)obj;

		long primaryKey = statisticByAgency.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<StatisticByAgency> toCacheModel() {
		StatisticByAgencyCacheModel statisticByAgencyCacheModel = new StatisticByAgencyCacheModel();

		statisticByAgencyCacheModel.statisticByAgencyId = getStatisticByAgencyId();

		statisticByAgencyCacheModel.groupId = getGroupId();

		statisticByAgencyCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			statisticByAgencyCacheModel.createDate = createDate.getTime();
		}
		else {
			statisticByAgencyCacheModel.createDate = Long.MIN_VALUE;
		}

		statisticByAgencyCacheModel.month = getMonth();

		statisticByAgencyCacheModel.year = getYear();

		statisticByAgencyCacheModel.govAgencyId = getGovAgencyId();

		String govAgencyId = statisticByAgencyCacheModel.govAgencyId;

		if ((govAgencyId != null) && (govAgencyId.length() == 0)) {
			statisticByAgencyCacheModel.govAgencyId = null;
		}

		statisticByAgencyCacheModel.receiveNumber = getReceiveNumber();

		statisticByAgencyCacheModel.onlineNumber = getOnlineNumber();

		statisticByAgencyCacheModel.onlineRatio = getOnlineRatio();

		statisticByAgencyCacheModel.finishNumber = getFinishNumber();

		statisticByAgencyCacheModel.ontimeNumber = getOntimeNumber();

		statisticByAgencyCacheModel.ontimeRatio = getOntimeRatio();

		statisticByAgencyCacheModel.delayDaysAvg = getDelayDaysAvg();

		return statisticByAgencyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{statisticByAgencyId=");
		sb.append(getStatisticByAgencyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", month=");
		sb.append(getMonth());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", govAgencyId=");
		sb.append(getGovAgencyId());
		sb.append(", receiveNumber=");
		sb.append(getReceiveNumber());
		sb.append(", onlineNumber=");
		sb.append(getOnlineNumber());
		sb.append(", onlineRatio=");
		sb.append(getOnlineRatio());
		sb.append(", finishNumber=");
		sb.append(getFinishNumber());
		sb.append(", ontimeNumber=");
		sb.append(getOntimeNumber());
		sb.append(", ontimeRatio=");
		sb.append(getOntimeRatio());
		sb.append(", delayDaysAvg=");
		sb.append(getDelayDaysAvg());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.dossiermgt.model.StatisticByAgency");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>statisticByAgencyId</column-name><column-value><![CDATA[");
		sb.append(getStatisticByAgencyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>month</column-name><column-value><![CDATA[");
		sb.append(getMonth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyId</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>receiveNumber</column-name><column-value><![CDATA[");
		sb.append(getReceiveNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>onlineNumber</column-name><column-value><![CDATA[");
		sb.append(getOnlineNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>onlineRatio</column-name><column-value><![CDATA[");
		sb.append(getOnlineRatio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>finishNumber</column-name><column-value><![CDATA[");
		sb.append(getFinishNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ontimeNumber</column-name><column-value><![CDATA[");
		sb.append(getOntimeNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ontimeRatio</column-name><column-value><![CDATA[");
		sb.append(getOntimeRatio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>delayDaysAvg</column-name><column-value><![CDATA[");
		sb.append(getDelayDaysAvg());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = StatisticByAgency.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			StatisticByAgency.class
		};
	private long _statisticByAgencyId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private int _month;
	private int _year;
	private String _govAgencyId;
	private long _receiveNumber;
	private long _onlineNumber;
	private double _onlineRatio;
	private int _finishNumber;
	private int _ontimeNumber;
	private double _ontimeRatio;
	private double _delayDaysAvg;
	private StatisticByAgency _escapedModel;
}