/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProcessOrder service. Represents a row in the &quot;oep_processmgt_ProcessOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.processmgt.model.impl.ProcessOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.processmgt.model.impl.ProcessOrderImpl}.
 * </p>
 *
 * @author trungdk
 * @see ProcessOrder
 * @see org.oep.core.processmgt.model.impl.ProcessOrderImpl
 * @see org.oep.core.processmgt.model.impl.ProcessOrderModelImpl
 * @generated
 */
public interface ProcessOrderModel extends BaseModel<ProcessOrder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a process order model instance should use the {@link ProcessOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this process order.
	 *
	 * @return the primary key of this process order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this process order.
	 *
	 * @param primaryKey the primary key of this process order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the process order ID of this process order.
	 *
	 * @return the process order ID of this process order
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order ID of this process order.
	 *
	 * @param processOrderId the process order ID of this process order
	 */
	public void setProcessOrderId(long processOrderId);

	/**
	 * Returns the user ID of this process order.
	 *
	 * @return the user ID of this process order
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this process order.
	 *
	 * @param userId the user ID of this process order
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this process order.
	 *
	 * @return the user uuid of this process order
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this process order.
	 *
	 * @param userUuid the user uuid of this process order
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this process order.
	 *
	 * @return the group ID of this process order
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this process order.
	 *
	 * @param groupId the group ID of this process order
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this process order.
	 *
	 * @return the company ID of this process order
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this process order.
	 *
	 * @param companyId the company ID of this process order
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this process order.
	 *
	 * @return the create date of this process order
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this process order.
	 *
	 * @param createDate the create date of this process order
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this process order.
	 *
	 * @return the modified date of this process order
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this process order.
	 *
	 * @param modifiedDate the modified date of this process order
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this process order.
	 *
	 * @return the organization ID of this process order
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this process order.
	 *
	 * @param organizationId the organization ID of this process order
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the parent process order ID of this process order.
	 *
	 * @return the parent process order ID of this process order
	 */
	public long getParentProcessOrderId();

	/**
	 * Sets the parent process order ID of this process order.
	 *
	 * @param parentProcessOrderId the parent process order ID of this process order
	 */
	public void setParentProcessOrderId(long parentProcessOrderId);

	/**
	 * Returns the dossier ID of this process order.
	 *
	 * @return the dossier ID of this process order
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this process order.
	 *
	 * @param dossierId the dossier ID of this process order
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier process ID of this process order.
	 *
	 * @return the dossier process ID of this process order
	 */
	public long getDossierProcessId();

	/**
	 * Sets the dossier process ID of this process order.
	 *
	 * @param dossierProcessId the dossier process ID of this process order
	 */
	public void setDossierProcessId(long dossierProcessId);

	/**
	 * Returns the dossier step ID of this process order.
	 *
	 * @return the dossier step ID of this process order
	 */
	public long getDossierStepId();

	/**
	 * Sets the dossier step ID of this process order.
	 *
	 * @param dossierStepId the dossier step ID of this process order
	 */
	public void setDossierStepId(long dossierStepId);

	/**
	 * Returns the dossier status of this process order.
	 *
	 * @return the dossier status of this process order
	 */
	@AutoEscape
	public String getDossierStatus();

	/**
	 * Sets the dossier status of this process order.
	 *
	 * @param dossierStatus the dossier status of this process order
	 */
	public void setDossierStatus(String dossierStatus);

	/**
	 * Returns the dossier resume of this process order.
	 *
	 * @return the dossier resume of this process order
	 */
	@AutoEscape
	public String getDossierResume();

	/**
	 * Sets the dossier resume of this process order.
	 *
	 * @param dossierResume the dossier resume of this process order
	 */
	public void setDossierResume(String dossierResume);

	/**
	 * Returns the step date of this process order.
	 *
	 * @return the step date of this process order
	 */
	public Date getStepDate();

	/**
	 * Sets the step date of this process order.
	 *
	 * @param stepDate the step date of this process order
	 */
	public void setStepDate(Date stepDate);

	/**
	 * Returns the step note of this process order.
	 *
	 * @return the step note of this process order
	 */
	@AutoEscape
	public String getStepNote();

	/**
	 * Sets the step note of this process order.
	 *
	 * @param stepNote the step note of this process order
	 */
	public void setStepNote(String stepNote);

	/**
	 * Returns the assign to user ID of this process order.
	 *
	 * @return the assign to user ID of this process order
	 */
	public long getAssignToUserId();

	/**
	 * Sets the assign to user ID of this process order.
	 *
	 * @param assignToUserId the assign to user ID of this process order
	 */
	public void setAssignToUserId(long assignToUserId);

	/**
	 * Returns the assign to user uuid of this process order.
	 *
	 * @return the assign to user uuid of this process order
	 * @throws SystemException if a system exception occurred
	 */
	public String getAssignToUserUuid() throws SystemException;

	/**
	 * Sets the assign to user uuid of this process order.
	 *
	 * @param assignToUserUuid the assign to user uuid of this process order
	 */
	public void setAssignToUserUuid(String assignToUserUuid);

	/**
	 * Returns the current condition of this process order.
	 *
	 * @return the current condition of this process order
	 */
	@AutoEscape
	public String getCurrentCondition();

	/**
	 * Sets the current condition of this process order.
	 *
	 * @param currentCondition the current condition of this process order
	 */
	public void setCurrentCondition(String currentCondition);

	/**
	 * Returns the end state of this process order.
	 *
	 * @return the end state of this process order
	 */
	public int getEndState();

	/**
	 * Sets the end state of this process order.
	 *
	 * @param endState the end state of this process order
	 */
	public void setEndState(int endState);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProcessOrder processOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProcessOrder> toCacheModel();

	@Override
	public ProcessOrder toEscapedModel();

	@Override
	public ProcessOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}