/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TransitionHistory service. Represents a row in the &quot;oep_processmgt_TransitionHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.processmgt.model.impl.TransitionHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.processmgt.model.impl.TransitionHistoryImpl}.
 * </p>
 *
 * @author trungdk
 * @see TransitionHistory
 * @see org.oep.core.processmgt.model.impl.TransitionHistoryImpl
 * @see org.oep.core.processmgt.model.impl.TransitionHistoryModelImpl
 * @generated
 */
public interface TransitionHistoryModel extends BaseModel<TransitionHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a transition history model instance should use the {@link TransitionHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this transition history.
	 *
	 * @return the primary key of this transition history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this transition history.
	 *
	 * @param primaryKey the primary key of this transition history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the transition history ID of this transition history.
	 *
	 * @return the transition history ID of this transition history
	 */
	public long getTransitionHistoryId();

	/**
	 * Sets the transition history ID of this transition history.
	 *
	 * @param transitionHistoryId the transition history ID of this transition history
	 */
	public void setTransitionHistoryId(long transitionHistoryId);

	/**
	 * Returns the user ID of this transition history.
	 *
	 * @return the user ID of this transition history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this transition history.
	 *
	 * @param userId the user ID of this transition history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this transition history.
	 *
	 * @return the user uuid of this transition history
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this transition history.
	 *
	 * @param userUuid the user uuid of this transition history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this transition history.
	 *
	 * @return the group ID of this transition history
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this transition history.
	 *
	 * @param groupId the group ID of this transition history
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this transition history.
	 *
	 * @return the company ID of this transition history
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this transition history.
	 *
	 * @param companyId the company ID of this transition history
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this transition history.
	 *
	 * @return the create date of this transition history
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this transition history.
	 *
	 * @param createDate the create date of this transition history
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the dossier ID of this transition history.
	 *
	 * @return the dossier ID of this transition history
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this transition history.
	 *
	 * @param dossierId the dossier ID of this transition history
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the process order ID of this transition history.
	 *
	 * @return the process order ID of this transition history
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order ID of this transition history.
	 *
	 * @param processOrderId the process order ID of this transition history
	 */
	public void setProcessOrderId(long processOrderId);

	/**
	 * Returns the days doing of this transition history.
	 *
	 * @return the days doing of this transition history
	 */
	public int getDaysDoing();

	/**
	 * Sets the days doing of this transition history.
	 *
	 * @param daysDoing the days doing of this transition history
	 */
	public void setDaysDoing(int daysDoing);

	/**
	 * Returns the days delay of this transition history.
	 *
	 * @return the days delay of this transition history
	 */
	public int getDaysDelay();

	/**
	 * Sets the days delay of this transition history.
	 *
	 * @param daysDelay the days delay of this transition history
	 */
	public void setDaysDelay(int daysDelay);

	/**
	 * Returns the start date of this transition history.
	 *
	 * @return the start date of this transition history
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this transition history.
	 *
	 * @param startDate the start date of this transition history
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the step transition ID of this transition history.
	 *
	 * @return the step transition ID of this transition history
	 */
	public long getStepTransitionId();

	/**
	 * Sets the step transition ID of this transition history.
	 *
	 * @param stepTransitionId the step transition ID of this transition history
	 */
	public void setStepTransitionId(long stepTransitionId);

	/**
	 * Returns the pre dossier step ID of this transition history.
	 *
	 * @return the pre dossier step ID of this transition history
	 */
	public long getPreDossierStepId();

	/**
	 * Sets the pre dossier step ID of this transition history.
	 *
	 * @param preDossierStepId the pre dossier step ID of this transition history
	 */
	public void setPreDossierStepId(long preDossierStepId);

	/**
	 * Returns the post dossier step ID of this transition history.
	 *
	 * @return the post dossier step ID of this transition history
	 */
	public long getPostDossierStepId();

	/**
	 * Sets the post dossier step ID of this transition history.
	 *
	 * @param postDossierStepId the post dossier step ID of this transition history
	 */
	public void setPostDossierStepId(long postDossierStepId);

	/**
	 * Returns the transition name of this transition history.
	 *
	 * @return the transition name of this transition history
	 */
	@AutoEscape
	public String getTransitionName();

	/**
	 * Sets the transition name of this transition history.
	 *
	 * @param transitionName the transition name of this transition history
	 */
	public void setTransitionName(String transitionName);

	/**
	 * Returns the note of this transition history.
	 *
	 * @return the note of this transition history
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this transition history.
	 *
	 * @param note the note of this transition history
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TransitionHistory transitionHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TransitionHistory> toCacheModel();

	@Override
	public TransitionHistory toEscapedModel();

	@Override
	public TransitionHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}