/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierProcAgent service. Represents a row in the &quot;oep_dossiermgt_dossierprocagent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.dossiermgt.model.impl.DossierProcAgentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.dossiermgt.model.impl.DossierProcAgentImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierProcAgent
 * @see org.oep.core.dossiermgt.model.impl.DossierProcAgentImpl
 * @see org.oep.core.dossiermgt.model.impl.DossierProcAgentModelImpl
 * @generated
 */
public interface DossierProcAgentModel extends BaseModel<DossierProcAgent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier proc agent model instance should use the {@link DossierProcAgent} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier proc agent.
	 *
	 * @return the primary key of this dossier proc agent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier proc agent.
	 *
	 * @param primaryKey the primary key of this dossier proc agent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier proc agent ID of this dossier proc agent.
	 *
	 * @return the dossier proc agent ID of this dossier proc agent
	 */
	public long getDossierProcAgentId();

	/**
	 * Sets the dossier proc agent ID of this dossier proc agent.
	 *
	 * @param dossierProcAgentId the dossier proc agent ID of this dossier proc agent
	 */
	public void setDossierProcAgentId(long dossierProcAgentId);

	/**
	 * Returns the company ID of this dossier proc agent.
	 *
	 * @return the company ID of this dossier proc agent
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier proc agent.
	 *
	 * @param companyId the company ID of this dossier proc agent
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this dossier proc agent.
	 *
	 * @return the create date of this dossier proc agent
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier proc agent.
	 *
	 * @param createDate the create date of this dossier proc agent
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier proc agent.
	 *
	 * @return the modified date of this dossier proc agent
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier proc agent.
	 *
	 * @param modifiedDate the modified date of this dossier proc agent
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier proc ID of this dossier proc agent.
	 *
	 * @return the dossier proc ID of this dossier proc agent
	 */
	public long getDossierProcId();

	/**
	 * Sets the dossier proc ID of this dossier proc agent.
	 *
	 * @param dossierProcId the dossier proc ID of this dossier proc agent
	 */
	public void setDossierProcId(long dossierProcId);

	/**
	 * Returns the gov agency ID of this dossier proc agent.
	 *
	 * @return the gov agency ID of this dossier proc agent
	 */
	@AutoEscape
	public String getGovAgencyId();

	/**
	 * Sets the gov agency ID of this dossier proc agent.
	 *
	 * @param govAgencyId the gov agency ID of this dossier proc agent
	 */
	public void setGovAgencyId(String govAgencyId);

	/**
	 * Returns the gov agency name of this dossier proc agent.
	 *
	 * @return the gov agency name of this dossier proc agent
	 */
	@AutoEscape
	public String getGovAgencyName();

	/**
	 * Sets the gov agency name of this dossier proc agent.
	 *
	 * @param govAgencyName the gov agency name of this dossier proc agent
	 */
	public void setGovAgencyName(String govAgencyName);

	/**
	 * Returns the eb partner ship ID of this dossier proc agent.
	 *
	 * @return the eb partner ship ID of this dossier proc agent
	 */
	public long getEbPartnerShipId();

	/**
	 * Sets the eb partner ship ID of this dossier proc agent.
	 *
	 * @param ebPartnerShipId the eb partner ship ID of this dossier proc agent
	 */
	public void setEbPartnerShipId(long ebPartnerShipId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DossierProcAgent dossierProcAgent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DossierProcAgent> toCacheModel();

	@Override
	public DossierProcAgent toEscapedModel();

	@Override
	public DossierProcAgent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}