/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierProc service. Represents a row in the &quot;oep_dossiermgt_dossierproc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.dossiermgt.model.impl.DossierProcModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.dossiermgt.model.impl.DossierProcImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierProc
 * @see org.oep.core.dossiermgt.model.impl.DossierProcImpl
 * @see org.oep.core.dossiermgt.model.impl.DossierProcModelImpl
 * @generated
 */
public interface DossierProcModel extends BaseModel<DossierProc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier proc model instance should use the {@link DossierProc} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier proc.
	 *
	 * @return the primary key of this dossier proc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier proc.
	 *
	 * @param primaryKey the primary key of this dossier proc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier proc ID of this dossier proc.
	 *
	 * @return the dossier proc ID of this dossier proc
	 */
	public long getDossierProcId();

	/**
	 * Sets the dossier proc ID of this dossier proc.
	 *
	 * @param dossierProcId the dossier proc ID of this dossier proc
	 */
	public void setDossierProcId(long dossierProcId);

	/**
	 * Returns the user ID of this dossier proc.
	 *
	 * @return the user ID of this dossier proc
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dossier proc.
	 *
	 * @param userId the user ID of this dossier proc
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dossier proc.
	 *
	 * @return the user uuid of this dossier proc
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dossier proc.
	 *
	 * @param userUuid the user uuid of this dossier proc
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this dossier proc.
	 *
	 * @return the group ID of this dossier proc
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dossier proc.
	 *
	 * @param groupId the group ID of this dossier proc
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dossier proc.
	 *
	 * @return the company ID of this dossier proc
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier proc.
	 *
	 * @param companyId the company ID of this dossier proc
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this dossier proc.
	 *
	 * @return the create date of this dossier proc
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier proc.
	 *
	 * @param createDate the create date of this dossier proc
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier proc.
	 *
	 * @return the modified date of this dossier proc
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier proc.
	 *
	 * @param modifiedDate the modified date of this dossier proc
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier proc no of this dossier proc.
	 *
	 * @return the dossier proc no of this dossier proc
	 */
	@AutoEscape
	public String getDossierProcNo();

	/**
	 * Sets the dossier proc no of this dossier proc.
	 *
	 * @param dossierProcNo the dossier proc no of this dossier proc
	 */
	public void setDossierProcNo(String dossierProcNo);

	/**
	 * Returns the name of this dossier proc.
	 *
	 * @return the name of this dossier proc
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dossier proc.
	 *
	 * @param name the name of this dossier proc
	 */
	public void setName(String name);

	/**
	 * Returns the en name of this dossier proc.
	 *
	 * @return the en name of this dossier proc
	 */
	@AutoEscape
	public String getEnName();

	/**
	 * Sets the en name of this dossier proc.
	 *
	 * @param enName the en name of this dossier proc
	 */
	public void setEnName(String enName);

	/**
	 * Returns the short name of this dossier proc.
	 *
	 * @return the short name of this dossier proc
	 */
	@AutoEscape
	public String getShortName();

	/**
	 * Sets the short name of this dossier proc.
	 *
	 * @param shortName the short name of this dossier proc
	 */
	public void setShortName(String shortName);

	/**
	 * Returns the process description of this dossier proc.
	 *
	 * @return the process description of this dossier proc
	 */
	@AutoEscape
	public String getProcessDescription();

	/**
	 * Sets the process description of this dossier proc.
	 *
	 * @param processDescription the process description of this dossier proc
	 */
	public void setProcessDescription(String processDescription);

	/**
	 * Returns the method description of this dossier proc.
	 *
	 * @return the method description of this dossier proc
	 */
	@AutoEscape
	public String getMethodDescription();

	/**
	 * Sets the method description of this dossier proc.
	 *
	 * @param methodDescription the method description of this dossier proc
	 */
	public void setMethodDescription(String methodDescription);

	/**
	 * Returns the dossier description of this dossier proc.
	 *
	 * @return the dossier description of this dossier proc
	 */
	@AutoEscape
	public String getDossierDescription();

	/**
	 * Sets the dossier description of this dossier proc.
	 *
	 * @param dossierDescription the dossier description of this dossier proc
	 */
	public void setDossierDescription(String dossierDescription);

	/**
	 * Returns the condition description of this dossier proc.
	 *
	 * @return the condition description of this dossier proc
	 */
	@AutoEscape
	public String getConditionDescription();

	/**
	 * Sets the condition description of this dossier proc.
	 *
	 * @param conditionDescription the condition description of this dossier proc
	 */
	public void setConditionDescription(String conditionDescription);

	/**
	 * Returns the duration description of this dossier proc.
	 *
	 * @return the duration description of this dossier proc
	 */
	@AutoEscape
	public String getDurationDescription();

	/**
	 * Sets the duration description of this dossier proc.
	 *
	 * @param durationDescription the duration description of this dossier proc
	 */
	public void setDurationDescription(String durationDescription);

	/**
	 * Returns the actors description of this dossier proc.
	 *
	 * @return the actors description of this dossier proc
	 */
	@AutoEscape
	public String getActorsDescription();

	/**
	 * Sets the actors description of this dossier proc.
	 *
	 * @param actorsDescription the actors description of this dossier proc
	 */
	public void setActorsDescription(String actorsDescription);

	/**
	 * Returns the results description of this dossier proc.
	 *
	 * @return the results description of this dossier proc
	 */
	@AutoEscape
	public String getResultsDescription();

	/**
	 * Sets the results description of this dossier proc.
	 *
	 * @param resultsDescription the results description of this dossier proc
	 */
	public void setResultsDescription(String resultsDescription);

	/**
	 * Returns the records description of this dossier proc.
	 *
	 * @return the records description of this dossier proc
	 */
	@AutoEscape
	public String getRecordsDescription();

	/**
	 * Sets the records description of this dossier proc.
	 *
	 * @param recordsDescription the records description of this dossier proc
	 */
	public void setRecordsDescription(String recordsDescription);

	/**
	 * Returns the fee description of this dossier proc.
	 *
	 * @return the fee description of this dossier proc
	 */
	@AutoEscape
	public String getFeeDescription();

	/**
	 * Sets the fee description of this dossier proc.
	 *
	 * @param feeDescription the fee description of this dossier proc
	 */
	public void setFeeDescription(String feeDescription);

	/**
	 * Returns the instructions description of this dossier proc.
	 *
	 * @return the instructions description of this dossier proc
	 */
	@AutoEscape
	public String getInstructionsDescription();

	/**
	 * Sets the instructions description of this dossier proc.
	 *
	 * @param instructionsDescription the instructions description of this dossier proc
	 */
	public void setInstructionsDescription(String instructionsDescription);

	/**
	 * Returns the administration no of this dossier proc.
	 *
	 * @return the administration no of this dossier proc
	 */
	@AutoEscape
	public String getAdministrationNo();

	/**
	 * Sets the administration no of this dossier proc.
	 *
	 * @param administrationNo the administration no of this dossier proc
	 */
	public void setAdministrationNo(String administrationNo);

	/**
	 * Returns the administration name of this dossier proc.
	 *
	 * @return the administration name of this dossier proc
	 */
	@AutoEscape
	public String getAdministrationName();

	/**
	 * Sets the administration name of this dossier proc.
	 *
	 * @param administrationName the administration name of this dossier proc
	 */
	public void setAdministrationName(String administrationName);

	/**
	 * Returns the domain no of this dossier proc.
	 *
	 * @return the domain no of this dossier proc
	 */
	@AutoEscape
	public String getDomainNo();

	/**
	 * Sets the domain no of this dossier proc.
	 *
	 * @param domainNo the domain no of this dossier proc
	 */
	public void setDomainNo(String domainNo);

	/**
	 * Returns the domain name of this dossier proc.
	 *
	 * @return the domain name of this dossier proc
	 */
	@AutoEscape
	public String getDomainName();

	/**
	 * Sets the domain name of this dossier proc.
	 *
	 * @param domainName the domain name of this dossier proc
	 */
	public void setDomainName(String domainName);

	/**
	 * Returns the effect date of this dossier proc.
	 *
	 * @return the effect date of this dossier proc
	 */
	public Date getEffectDate();

	/**
	 * Sets the effect date of this dossier proc.
	 *
	 * @param effectDate the effect date of this dossier proc
	 */
	public void setEffectDate(Date effectDate);

	/**
	 * Returns the expire date of this dossier proc.
	 *
	 * @return the expire date of this dossier proc
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this dossier proc.
	 *
	 * @param expireDate the expire date of this dossier proc
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the active of this dossier proc.
	 *
	 * @return the active of this dossier proc
	 */
	public int getActive();

	/**
	 * Sets the active of this dossier proc.
	 *
	 * @param active the active of this dossier proc
	 */
	public void setActive(int active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DossierProc dossierProc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DossierProc> toCacheModel();

	@Override
	public DossierProc toEscapedModel();

	@Override
	public DossierProc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}