/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.datamgt.dictionary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DictData service. Represents a row in the &quot;oep_datamgt_dictdata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.datamgt.dictionary.model.impl.DictDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.datamgt.dictionary.model.impl.DictDataImpl}.
 * </p>
 *
 * @author TrungDK
 * @see DictData
 * @see org.oep.core.datamgt.dictionary.model.impl.DictDataImpl
 * @see org.oep.core.datamgt.dictionary.model.impl.DictDataModelImpl
 * @generated
 */
public interface DictDataModel extends BaseModel<DictData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dictionary data model instance should use the {@link DictData} interface instead.
	 */

	/**
	 * Returns the primary key of this dictionary data.
	 *
	 * @return the primary key of this dictionary data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dictionary data.
	 *
	 * @param primaryKey the primary key of this dictionary data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dict data ID of this dictionary data.
	 *
	 * @return the dict data ID of this dictionary data
	 */
	public long getDictDataId();

	/**
	 * Sets the dict data ID of this dictionary data.
	 *
	 * @param dictDataId the dict data ID of this dictionary data
	 */
	public void setDictDataId(long dictDataId);

	/**
	 * Returns the company ID of this dictionary data.
	 *
	 * @return the company ID of this dictionary data
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dictionary data.
	 *
	 * @param companyId the company ID of this dictionary data
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dictionary data.
	 *
	 * @return the user ID of this dictionary data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dictionary data.
	 *
	 * @param userId the user ID of this dictionary data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dictionary data.
	 *
	 * @return the user uuid of this dictionary data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dictionary data.
	 *
	 * @param userUuid the user uuid of this dictionary data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this dictionary data.
	 *
	 * @return the group ID of this dictionary data
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dictionary data.
	 *
	 * @param groupId the group ID of this dictionary data
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this dictionary data.
	 *
	 * @return the create date of this dictionary data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dictionary data.
	 *
	 * @param createDate the create date of this dictionary data
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dictionary data.
	 *
	 * @return the modified date of this dictionary data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dictionary data.
	 *
	 * @param modifiedDate the modified date of this dictionary data
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the collection name of this dictionary data.
	 *
	 * @return the collection name of this dictionary data
	 */
	@AutoEscape
	public String getCollectionName();

	/**
	 * Sets the collection name of this dictionary data.
	 *
	 * @param collectionName the collection name of this dictionary data
	 */
	public void setCollectionName(String collectionName);

	/**
	 * Returns the data code of this dictionary data.
	 *
	 * @return the data code of this dictionary data
	 */
	@AutoEscape
	public String getDataCode();

	/**
	 * Sets the data code of this dictionary data.
	 *
	 * @param dataCode the data code of this dictionary data
	 */
	public void setDataCode(String dataCode);

	/**
	 * Returns the node_1 of this dictionary data.
	 *
	 * @return the node_1 of this dictionary data
	 */
	@AutoEscape
	public String getNode_1();

	/**
	 * Sets the node_1 of this dictionary data.
	 *
	 * @param node_1 the node_1 of this dictionary data
	 */
	public void setNode_1(String node_1);

	/**
	 * Returns the node_2 of this dictionary data.
	 *
	 * @return the node_2 of this dictionary data
	 */
	@AutoEscape
	public String getNode_2();

	/**
	 * Sets the node_2 of this dictionary data.
	 *
	 * @param node_2 the node_2 of this dictionary data
	 */
	public void setNode_2(String node_2);

	/**
	 * Returns the node_3 of this dictionary data.
	 *
	 * @return the node_3 of this dictionary data
	 */
	@AutoEscape
	public String getNode_3();

	/**
	 * Sets the node_3 of this dictionary data.
	 *
	 * @param node_3 the node_3 of this dictionary data
	 */
	public void setNode_3(String node_3);

	/**
	 * Returns the node_4 of this dictionary data.
	 *
	 * @return the node_4 of this dictionary data
	 */
	@AutoEscape
	public String getNode_4();

	/**
	 * Sets the node_4 of this dictionary data.
	 *
	 * @param node_4 the node_4 of this dictionary data
	 */
	public void setNode_4(String node_4);

	/**
	 * Returns the node_5 of this dictionary data.
	 *
	 * @return the node_5 of this dictionary data
	 */
	@AutoEscape
	public String getNode_5();

	/**
	 * Sets the node_5 of this dictionary data.
	 *
	 * @param node_5 the node_5 of this dictionary data
	 */
	public void setNode_5(String node_5);

	/**
	 * Returns the data level of this dictionary data.
	 *
	 * @return the data level of this dictionary data
	 */
	public int getDataLevel();

	/**
	 * Sets the data level of this dictionary data.
	 *
	 * @param dataLevel the data level of this dictionary data
	 */
	public void setDataLevel(int dataLevel);

	/**
	 * Returns the title of this dictionary data.
	 *
	 * @return the title of this dictionary data
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this dictionary data.
	 *
	 * @param title the title of this dictionary data
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this dictionary data.
	 *
	 * @return the description of this dictionary data
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dictionary data.
	 *
	 * @param description the description of this dictionary data
	 */
	public void setDescription(String description);

	/**
	 * Returns the validated from of this dictionary data.
	 *
	 * @return the validated from of this dictionary data
	 */
	public Date getValidatedFrom();

	/**
	 * Sets the validated from of this dictionary data.
	 *
	 * @param validatedFrom the validated from of this dictionary data
	 */
	public void setValidatedFrom(Date validatedFrom);

	/**
	 * Returns the validated to of this dictionary data.
	 *
	 * @return the validated to of this dictionary data
	 */
	public Date getValidatedTo();

	/**
	 * Sets the validated to of this dictionary data.
	 *
	 * @param validatedTo the validated to of this dictionary data
	 */
	public void setValidatedTo(Date validatedTo);

	/**
	 * Returns the status of this dictionary data.
	 *
	 * @return the status of this dictionary data
	 */
	public int getStatus();

	/**
	 * Sets the status of this dictionary data.
	 *
	 * @param status the status of this dictionary data
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DictData dictData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DictData> toCacheModel();

	@Override
	public DictData toEscapedModel();

	@Override
	public DictData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}