/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.processmgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DossierProc2Role service. Represents a row in the &quot;oep_processmgt_dossierproc2role&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.processmgt.model.impl.DossierProc2RoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.processmgt.model.impl.DossierProc2RoleImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierProc2Role
 * @see org.oep.processmgt.model.impl.DossierProc2RoleImpl
 * @see org.oep.processmgt.model.impl.DossierProc2RoleModelImpl
 * @generated
 */
public interface DossierProc2RoleModel extends BaseModel<DossierProc2Role> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier proc2 role model instance should use the {@link DossierProc2Role} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier proc2 role.
	 *
	 * @return the primary key of this dossier proc2 role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier proc2 role.
	 *
	 * @param primaryKey the primary key of this dossier proc2 role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier proc2 role ID of this dossier proc2 role.
	 *
	 * @return the dossier proc2 role ID of this dossier proc2 role
	 */
	public long getDossierProc2RoleId();

	/**
	 * Sets the dossier proc2 role ID of this dossier proc2 role.
	 *
	 * @param dossierProc2RoleId the dossier proc2 role ID of this dossier proc2 role
	 */
	public void setDossierProc2RoleId(long dossierProc2RoleId);

	/**
	 * Returns the dossier proc ID of this dossier proc2 role.
	 *
	 * @return the dossier proc ID of this dossier proc2 role
	 */
	public long getDossierProcId();

	/**
	 * Sets the dossier proc ID of this dossier proc2 role.
	 *
	 * @param dossierProcId the dossier proc ID of this dossier proc2 role
	 */
	public void setDossierProcId(long dossierProcId);

	/**
	 * Returns the role ID of this dossier proc2 role.
	 *
	 * @return the role ID of this dossier proc2 role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this dossier proc2 role.
	 *
	 * @param roleId the role ID of this dossier proc2 role
	 */
	public void setRoleId(long roleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DossierProc2Role dossierProc2Role);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DossierProc2Role> toCacheModel();

	@Override
	public DossierProc2Role toEscapedModel();

	@Override
	public DossierProc2Role toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}