/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.datamgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DictCollection service. Represents a row in the &quot;oep_datamgt_dictcollection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.datamgt.model.impl.DictCollectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.datamgt.model.impl.DictCollectionImpl}.
 * </p>
 *
 * @author NQMINH
 * @see DictCollection
 * @see org.oep.datamgt.model.impl.DictCollectionImpl
 * @see org.oep.datamgt.model.impl.DictCollectionModelImpl
 * @generated
 */
public interface DictCollectionModel extends BaseModel<DictCollection> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dictionary collection model instance should use the {@link DictCollection} interface instead.
	 */

	/**
	 * Returns the primary key of this dictionary collection.
	 *
	 * @return the primary key of this dictionary collection
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dictionary collection.
	 *
	 * @param primaryKey the primary key of this dictionary collection
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dict collection ID of this dictionary collection.
	 *
	 * @return the dict collection ID of this dictionary collection
	 */
	public long getDictCollectionId();

	/**
	 * Sets the dict collection ID of this dictionary collection.
	 *
	 * @param dictCollectionId the dict collection ID of this dictionary collection
	 */
	public void setDictCollectionId(long dictCollectionId);

	/**
	 * Returns the company ID of this dictionary collection.
	 *
	 * @return the company ID of this dictionary collection
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dictionary collection.
	 *
	 * @param companyId the company ID of this dictionary collection
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dictionary collection.
	 *
	 * @return the group ID of this dictionary collection
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dictionary collection.
	 *
	 * @param groupId the group ID of this dictionary collection
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this dictionary collection.
	 *
	 * @return the user ID of this dictionary collection
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dictionary collection.
	 *
	 * @param userId the user ID of this dictionary collection
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dictionary collection.
	 *
	 * @return the user uuid of this dictionary collection
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dictionary collection.
	 *
	 * @param userUuid the user uuid of this dictionary collection
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dictionary collection.
	 *
	 * @return the create date of this dictionary collection
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dictionary collection.
	 *
	 * @param createDate the create date of this dictionary collection
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dictionary collection.
	 *
	 * @return the modified date of this dictionary collection
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dictionary collection.
	 *
	 * @param modifiedDate the modified date of this dictionary collection
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this dictionary collection.
	 *
	 * @return the name of this dictionary collection
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dictionary collection.
	 *
	 * @param name the name of this dictionary collection
	 */
	public void setName(String name);

	/**
	 * Returns the version of this dictionary collection.
	 *
	 * @return the version of this dictionary collection
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this dictionary collection.
	 *
	 * @param version the version of this dictionary collection
	 */
	public void setVersion(String version);

	/**
	 * Returns the title of this dictionary collection.
	 *
	 * @return the title of this dictionary collection
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this dictionary collection.
	 *
	 * @param title the title of this dictionary collection
	 */
	public void setTitle(String title);

	/**
	 * Returns the validated from of this dictionary collection.
	 *
	 * @return the validated from of this dictionary collection
	 */
	public Date getValidatedFrom();

	/**
	 * Sets the validated from of this dictionary collection.
	 *
	 * @param validatedFrom the validated from of this dictionary collection
	 */
	public void setValidatedFrom(Date validatedFrom);

	/**
	 * Returns the validated to of this dictionary collection.
	 *
	 * @return the validated to of this dictionary collection
	 */
	public Date getValidatedTo();

	/**
	 * Sets the validated to of this dictionary collection.
	 *
	 * @param validatedTo the validated to of this dictionary collection
	 */
	public void setValidatedTo(Date validatedTo);

	/**
	 * Returns the status of this dictionary collection.
	 *
	 * @return the status of this dictionary collection
	 */
	public int getStatus();

	/**
	 * Sets the status of this dictionary collection.
	 *
	 * @param status the status of this dictionary collection
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DictCollection dictCollection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DictCollection> toCacheModel();

	@Override
	public DictCollection toEscapedModel();

	@Override
	public DictCollection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}