/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.datamgt.parameter.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.datamgt.parameter.model.UserParameter;
import org.oep.core.datamgt.parameter.model.UserParameterModel;
import org.oep.core.datamgt.parameter.model.UserParameterSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UserParameter service. Represents a row in the &quot;oep_datamgt_UserParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.datamgt.parameter.model.UserParameterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserParameterImpl}.
 * </p>
 *
 * @author TrungDK
 * @see UserParameterImpl
 * @see org.oep.core.datamgt.parameter.model.UserParameter
 * @see org.oep.core.datamgt.parameter.model.UserParameterModel
 * @generated
 */
@JSON(strict = true)
public class UserParameterModelImpl extends BaseModelImpl<UserParameter>
	implements UserParameterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user parameter model instance should use the {@link org.oep.core.datamgt.parameter.model.UserParameter} interface instead.
	 */
	public static final String TABLE_NAME = "oep_datamgt_UserParameter";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userParameterId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "applicationName", Types.VARCHAR },
			{ "parameterName", Types.VARCHAR },
			{ "title", Types.VARCHAR },
			{ "parameterValue", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_datamgt_UserParameter (userParameterId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,applicationName VARCHAR(75) null,parameterName VARCHAR(75) null,title VARCHAR(75) null,parameterValue VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table oep_datamgt_UserParameter";
	public static final String ORDER_BY_JPQL = " ORDER BY userParameter.userParameterId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_datamgt_UserParameter.userParameterId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.datamgt.parameter.model.UserParameter"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.datamgt.parameter.model.UserParameter"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UserParameter toModel(UserParameterSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UserParameter model = new UserParameterImpl();

		model.setUserParameterId(soapModel.getUserParameterId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setApplicationName(soapModel.getApplicationName());
		model.setParameterName(soapModel.getParameterName());
		model.setTitle(soapModel.getTitle());
		model.setParameterValue(soapModel.getParameterValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UserParameter> toModels(UserParameterSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UserParameter> models = new ArrayList<UserParameter>(soapModels.length);

		for (UserParameterSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.datamgt.parameter.model.UserParameter"));

	public UserParameterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userParameterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserParameterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userParameterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserParameter.class;
	}

	@Override
	public String getModelClassName() {
		return UserParameter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userParameterId", getUserParameterId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("applicationName", getApplicationName());
		attributes.put("parameterName", getParameterName());
		attributes.put("title", getTitle());
		attributes.put("parameterValue", getParameterValue());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userParameterId = (Long)attributes.get("userParameterId");

		if (userParameterId != null) {
			setUserParameterId(userParameterId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String applicationName = (String)attributes.get("applicationName");

		if (applicationName != null) {
			setApplicationName(applicationName);
		}

		String parameterName = (String)attributes.get("parameterName");

		if (parameterName != null) {
			setParameterName(parameterName);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String parameterValue = (String)attributes.get("parameterValue");

		if (parameterValue != null) {
			setParameterValue(parameterValue);
		}
	}

	@JSON
	@Override
	public long getUserParameterId() {
		return _userParameterId;
	}

	@Override
	public void setUserParameterId(long userParameterId) {
		_userParameterId = userParameterId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getApplicationName() {
		if (_applicationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicationName;
		}
	}

	@Override
	public void setApplicationName(String applicationName) {
		_applicationName = applicationName;
	}

	@JSON
	@Override
	public String getParameterName() {
		if (_parameterName == null) {
			return StringPool.BLANK;
		}
		else {
			return _parameterName;
		}
	}

	@Override
	public void setParameterName(String parameterName) {
		_parameterName = parameterName;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getParameterValue() {
		if (_parameterValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _parameterValue;
		}
	}

	@Override
	public void setParameterValue(String parameterValue) {
		_parameterValue = parameterValue;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			UserParameter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserParameter toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UserParameter)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserParameterImpl userParameterImpl = new UserParameterImpl();

		userParameterImpl.setUserParameterId(getUserParameterId());
		userParameterImpl.setUserId(getUserId());
		userParameterImpl.setGroupId(getGroupId());
		userParameterImpl.setCompanyId(getCompanyId());
		userParameterImpl.setCreateDate(getCreateDate());
		userParameterImpl.setModifiedDate(getModifiedDate());
		userParameterImpl.setApplicationName(getApplicationName());
		userParameterImpl.setParameterName(getParameterName());
		userParameterImpl.setTitle(getTitle());
		userParameterImpl.setParameterValue(getParameterValue());

		userParameterImpl.resetOriginalValues();

		return userParameterImpl;
	}

	@Override
	public int compareTo(UserParameter userParameter) {
		long primaryKey = userParameter.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UserParameter)) {
			return false;
		}

		UserParameter userParameter = (UserParameter)obj;

		long primaryKey = userParameter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UserParameter> toCacheModel() {
		UserParameterCacheModel userParameterCacheModel = new UserParameterCacheModel();

		userParameterCacheModel.userParameterId = getUserParameterId();

		userParameterCacheModel.userId = getUserId();

		userParameterCacheModel.groupId = getGroupId();

		userParameterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			userParameterCacheModel.createDate = createDate.getTime();
		}
		else {
			userParameterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userParameterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userParameterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		userParameterCacheModel.applicationName = getApplicationName();

		String applicationName = userParameterCacheModel.applicationName;

		if ((applicationName != null) && (applicationName.length() == 0)) {
			userParameterCacheModel.applicationName = null;
		}

		userParameterCacheModel.parameterName = getParameterName();

		String parameterName = userParameterCacheModel.parameterName;

		if ((parameterName != null) && (parameterName.length() == 0)) {
			userParameterCacheModel.parameterName = null;
		}

		userParameterCacheModel.title = getTitle();

		String title = userParameterCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			userParameterCacheModel.title = null;
		}

		userParameterCacheModel.parameterValue = getParameterValue();

		String parameterValue = userParameterCacheModel.parameterValue;

		if ((parameterValue != null) && (parameterValue.length() == 0)) {
			userParameterCacheModel.parameterValue = null;
		}

		return userParameterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{userParameterId=");
		sb.append(getUserParameterId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", applicationName=");
		sb.append(getApplicationName());
		sb.append(", parameterName=");
		sb.append(getParameterName());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", parameterValue=");
		sb.append(getParameterValue());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.datamgt.parameter.model.UserParameter");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userParameterId</column-name><column-value><![CDATA[");
		sb.append(getUserParameterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicationName</column-name><column-value><![CDATA[");
		sb.append(getApplicationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parameterName</column-name><column-value><![CDATA[");
		sb.append(getParameterName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parameterValue</column-name><column-value><![CDATA[");
		sb.append(getParameterValue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UserParameter.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UserParameter.class
		};
	private long _userParameterId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _applicationName;
	private String _parameterName;
	private String _title;
	private String _parameterValue;
	private UserParameter _escapedModel;
}