/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.processmgt.model.CreateFile;
import org.oep.core.processmgt.model.CreateFileModel;
import org.oep.core.processmgt.model.CreateFileSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CreateFile service. Represents a row in the &quot;oep_processmgt_createfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.processmgt.model.CreateFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CreateFileImpl}.
 * </p>
 *
 * @author trungdk
 * @see CreateFileImpl
 * @see org.oep.core.processmgt.model.CreateFile
 * @see org.oep.core.processmgt.model.CreateFileModel
 * @generated
 */
@JSON(strict = true)
public class CreateFileModelImpl extends BaseModelImpl<CreateFile>
	implements CreateFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a create file model instance should use the {@link org.oep.core.processmgt.model.CreateFile} interface instead.
	 */
	public static final String TABLE_NAME = "oep_processmgt_createfile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "createFileId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "processOrderId", Types.BIGINT },
			{ "dossierStepId", Types.BIGINT },
			{ "stepDate", Types.TIMESTAMP },
			{ "docFileId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_processmgt_createfile (createFileId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,createDate DATE null,processOrderId LONG,dossierStepId LONG,stepDate DATE null,docFileId LONG)";
	public static final String TABLE_SQL_DROP = "drop table oep_processmgt_createfile";
	public static final String ORDER_BY_JPQL = " ORDER BY createFile.createFileId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_processmgt_createfile.createFileId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.processmgt.model.CreateFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.processmgt.model.CreateFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CreateFile toModel(CreateFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CreateFile model = new CreateFileImpl();

		model.setCreateFileId(soapModel.getCreateFileId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setProcessOrderId(soapModel.getProcessOrderId());
		model.setDossierStepId(soapModel.getDossierStepId());
		model.setStepDate(soapModel.getStepDate());
		model.setDocFileId(soapModel.getDocFileId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CreateFile> toModels(CreateFileSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CreateFile> models = new ArrayList<CreateFile>(soapModels.length);

		for (CreateFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.processmgt.model.CreateFile"));

	public CreateFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _createFileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCreateFileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _createFileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CreateFile.class;
	}

	@Override
	public String getModelClassName() {
		return CreateFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("createFileId", getCreateFileId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("processOrderId", getProcessOrderId());
		attributes.put("dossierStepId", getDossierStepId());
		attributes.put("stepDate", getStepDate());
		attributes.put("docFileId", getDocFileId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long createFileId = (Long)attributes.get("createFileId");

		if (createFileId != null) {
			setCreateFileId(createFileId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long processOrderId = (Long)attributes.get("processOrderId");

		if (processOrderId != null) {
			setProcessOrderId(processOrderId);
		}

		Long dossierStepId = (Long)attributes.get("dossierStepId");

		if (dossierStepId != null) {
			setDossierStepId(dossierStepId);
		}

		Date stepDate = (Date)attributes.get("stepDate");

		if (stepDate != null) {
			setStepDate(stepDate);
		}

		Long docFileId = (Long)attributes.get("docFileId");

		if (docFileId != null) {
			setDocFileId(docFileId);
		}
	}

	@JSON
	@Override
	public long getCreateFileId() {
		return _createFileId;
	}

	@Override
	public void setCreateFileId(long createFileId) {
		_createFileId = createFileId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public long getProcessOrderId() {
		return _processOrderId;
	}

	@Override
	public void setProcessOrderId(long processOrderId) {
		_processOrderId = processOrderId;
	}

	@JSON
	@Override
	public long getDossierStepId() {
		return _dossierStepId;
	}

	@Override
	public void setDossierStepId(long dossierStepId) {
		_dossierStepId = dossierStepId;
	}

	@JSON
	@Override
	public Date getStepDate() {
		return _stepDate;
	}

	@Override
	public void setStepDate(Date stepDate) {
		_stepDate = stepDate;
	}

	@JSON
	@Override
	public long getDocFileId() {
		return _docFileId;
	}

	@Override
	public void setDocFileId(long docFileId) {
		_docFileId = docFileId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CreateFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CreateFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CreateFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CreateFileImpl createFileImpl = new CreateFileImpl();

		createFileImpl.setCreateFileId(getCreateFileId());
		createFileImpl.setUserId(getUserId());
		createFileImpl.setGroupId(getGroupId());
		createFileImpl.setCompanyId(getCompanyId());
		createFileImpl.setCreateDate(getCreateDate());
		createFileImpl.setProcessOrderId(getProcessOrderId());
		createFileImpl.setDossierStepId(getDossierStepId());
		createFileImpl.setStepDate(getStepDate());
		createFileImpl.setDocFileId(getDocFileId());

		createFileImpl.resetOriginalValues();

		return createFileImpl;
	}

	@Override
	public int compareTo(CreateFile createFile) {
		long primaryKey = createFile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CreateFile)) {
			return false;
		}

		CreateFile createFile = (CreateFile)obj;

		long primaryKey = createFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CreateFile> toCacheModel() {
		CreateFileCacheModel createFileCacheModel = new CreateFileCacheModel();

		createFileCacheModel.createFileId = getCreateFileId();

		createFileCacheModel.userId = getUserId();

		createFileCacheModel.groupId = getGroupId();

		createFileCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			createFileCacheModel.createDate = createDate.getTime();
		}
		else {
			createFileCacheModel.createDate = Long.MIN_VALUE;
		}

		createFileCacheModel.processOrderId = getProcessOrderId();

		createFileCacheModel.dossierStepId = getDossierStepId();

		Date stepDate = getStepDate();

		if (stepDate != null) {
			createFileCacheModel.stepDate = stepDate.getTime();
		}
		else {
			createFileCacheModel.stepDate = Long.MIN_VALUE;
		}

		createFileCacheModel.docFileId = getDocFileId();

		return createFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{createFileId=");
		sb.append(getCreateFileId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", processOrderId=");
		sb.append(getProcessOrderId());
		sb.append(", dossierStepId=");
		sb.append(getDossierStepId());
		sb.append(", stepDate=");
		sb.append(getStepDate());
		sb.append(", docFileId=");
		sb.append(getDocFileId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.processmgt.model.CreateFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>createFileId</column-name><column-value><![CDATA[");
		sb.append(getCreateFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>processOrderId</column-name><column-value><![CDATA[");
		sb.append(getProcessOrderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierStepId</column-name><column-value><![CDATA[");
		sb.append(getDossierStepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stepDate</column-name><column-value><![CDATA[");
		sb.append(getStepDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>docFileId</column-name><column-value><![CDATA[");
		sb.append(getDocFileId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CreateFile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CreateFile.class
		};
	private long _createFileId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _processOrderId;
	private long _dossierStepId;
	private Date _stepDate;
	private long _docFileId;
	private CreateFile _escapedModel;
}