/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.datamgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DictMetaData service. Represents a row in the &quot;oep_datamgt_dictmetadata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.datamgt.model.impl.DictMetaDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.datamgt.model.impl.DictMetaDataImpl}.
 * </p>
 *
 * @author NQMINH
 * @see DictMetaData
 * @see org.oep.core.datamgt.model.impl.DictMetaDataImpl
 * @see org.oep.core.datamgt.model.impl.DictMetaDataModelImpl
 * @generated
 */
public interface DictMetaDataModel extends BaseModel<DictMetaData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dictionary meta data model instance should use the {@link DictMetaData} interface instead.
	 */

	/**
	 * Returns the primary key of this dictionary meta data.
	 *
	 * @return the primary key of this dictionary meta data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dictionary meta data.
	 *
	 * @param primaryKey the primary key of this dictionary meta data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dict meta data ID of this dictionary meta data.
	 *
	 * @return the dict meta data ID of this dictionary meta data
	 */
	public long getDictMetaDataId();

	/**
	 * Sets the dict meta data ID of this dictionary meta data.
	 *
	 * @param dictMetaDataId the dict meta data ID of this dictionary meta data
	 */
	public void setDictMetaDataId(long dictMetaDataId);

	/**
	 * Returns the company ID of this dictionary meta data.
	 *
	 * @return the company ID of this dictionary meta data
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dictionary meta data.
	 *
	 * @param companyId the company ID of this dictionary meta data
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dictionary meta data.
	 *
	 * @return the group ID of this dictionary meta data
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dictionary meta data.
	 *
	 * @param groupId the group ID of this dictionary meta data
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this dictionary meta data.
	 *
	 * @return the user ID of this dictionary meta data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dictionary meta data.
	 *
	 * @param userId the user ID of this dictionary meta data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dictionary meta data.
	 *
	 * @return the user uuid of this dictionary meta data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dictionary meta data.
	 *
	 * @param userUuid the user uuid of this dictionary meta data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dictionary meta data.
	 *
	 * @return the create date of this dictionary meta data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dictionary meta data.
	 *
	 * @param createDate the create date of this dictionary meta data
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dictionary meta data.
	 *
	 * @return the modified date of this dictionary meta data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dictionary meta data.
	 *
	 * @param modifiedDate the modified date of this dictionary meta data
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dict data ID of this dictionary meta data.
	 *
	 * @return the dict data ID of this dictionary meta data
	 */
	public long getDictDataId();

	/**
	 * Sets the dict data ID of this dictionary meta data.
	 *
	 * @param dictDataId the dict data ID of this dictionary meta data
	 */
	public void setDictDataId(long dictDataId);

	/**
	 * Returns the attribute name of this dictionary meta data.
	 *
	 * @return the attribute name of this dictionary meta data
	 */
	@AutoEscape
	public String getAttributeName();

	/**
	 * Sets the attribute name of this dictionary meta data.
	 *
	 * @param attributeName the attribute name of this dictionary meta data
	 */
	public void setAttributeName(String attributeName);

	/**
	 * Returns the attribute value of this dictionary meta data.
	 *
	 * @return the attribute value of this dictionary meta data
	 */
	@AutoEscape
	public String getAttributeValue();

	/**
	 * Sets the attribute value of this dictionary meta data.
	 *
	 * @param attributeValue the attribute value of this dictionary meta data
	 */
	public void setAttributeValue(String attributeValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DictMetaData dictMetaData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DictMetaData> toCacheModel();

	@Override
	public DictMetaData toEscapedModel();

	@Override
	public DictMetaData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}