/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.ssomgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the Application service. Represents a row in the &quot;oep_ssomgt_application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.ssomgt.model.impl.ApplicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.ssomgt.model.impl.ApplicationImpl}.
 * </p>
 *
 * @author trungdk
 * @see Application
 * @see org.oep.core.ssomgt.model.impl.ApplicationImpl
 * @see org.oep.core.ssomgt.model.impl.ApplicationModelImpl
 * @generated
 */
public interface ApplicationModel extends BaseModel<Application> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application model instance should use the {@link Application} interface instead.
	 */

	/**
	 * Returns the primary key of this application.
	 *
	 * @return the primary key of this application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application.
	 *
	 * @param primaryKey the primary key of this application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application ID of this application.
	 *
	 * @return the application ID of this application
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this application.
	 *
	 * @param applicationId the application ID of this application
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the user ID of this application.
	 *
	 * @return the user ID of this application
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this application.
	 *
	 * @param userId the user ID of this application
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this application.
	 *
	 * @return the user uuid of this application
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this application.
	 *
	 * @param userUuid the user uuid of this application
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this application.
	 *
	 * @return the group ID of this application
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this application.
	 *
	 * @param groupId the group ID of this application
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this application.
	 *
	 * @return the company ID of this application
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this application.
	 *
	 * @param companyId the company ID of this application
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this application.
	 *
	 * @return the create date of this application
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this application.
	 *
	 * @param createDate the create date of this application
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application.
	 *
	 * @return the modified date of this application
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application.
	 *
	 * @param modifiedDate the modified date of this application
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the app code of this application.
	 *
	 * @return the app code of this application
	 */
	@AutoEscape
	public String getAppCode();

	/**
	 * Sets the app code of this application.
	 *
	 * @param appCode the app code of this application
	 */
	public void setAppCode(String appCode);

	/**
	 * Returns the app name of this application.
	 *
	 * @return the app name of this application
	 */
	@AutoEscape
	public String getAppName();

	/**
	 * Sets the app name of this application.
	 *
	 * @param appName the app name of this application
	 */
	public void setAppName(String appName);

	/**
	 * Returns the app pin of this application.
	 *
	 * @return the app pin of this application
	 */
	@AutoEscape
	public String getAppPin();

	/**
	 * Sets the app pin of this application.
	 *
	 * @param appPin the app pin of this application
	 */
	public void setAppPin(String appPin);

	/**
	 * Returns the app url of this application.
	 *
	 * @return the app url of this application
	 */
	@AutoEscape
	public String getAppUrl();

	/**
	 * Sets the app url of this application.
	 *
	 * @param appUrl the app url of this application
	 */
	public void setAppUrl(String appUrl);

	/**
	 * Returns the app big icon of this application.
	 *
	 * @return the app big icon of this application
	 */
	public Blob getAppBigIcon();

	/**
	 * Sets the app big icon of this application.
	 *
	 * @param appBigIcon the app big icon of this application
	 */
	public void setAppBigIcon(Blob appBigIcon);

	/**
	 * Returns the app small icon of this application.
	 *
	 * @return the app small icon of this application
	 */
	public Blob getAppSmallIcon();

	/**
	 * Sets the app small icon of this application.
	 *
	 * @param appSmallIcon the app small icon of this application
	 */
	public void setAppSmallIcon(Blob appSmallIcon);

	/**
	 * Returns the ping time of this application.
	 *
	 * @return the ping time of this application
	 */
	public Date getPingTime();

	/**
	 * Sets the ping time of this application.
	 *
	 * @param pingTime the ping time of this application
	 */
	public void setPingTime(Date pingTime);

	/**
	 * Returns the sequence no of this application.
	 *
	 * @return the sequence no of this application
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this application.
	 *
	 * @param sequenceNo the sequence no of this application
	 */
	public void setSequenceNo(int sequenceNo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Application application);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Application> toCacheModel();

	@Override
	public Application toEscapedModel();

	@Override
	public Application toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}