/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.ssomgt.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppRole2Employee service. Represents a row in the &quot;oep_ssomgt_approle2employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.ssomgt.model.impl.AppRole2EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.ssomgt.model.impl.AppRole2EmployeeImpl}.
 * </p>
 *
 * @author trungdk
 * @see AppRole2Employee
 * @see org.oep.core.ssomgt.model.impl.AppRole2EmployeeImpl
 * @see org.oep.core.ssomgt.model.impl.AppRole2EmployeeModelImpl
 * @generated
 */
public interface AppRole2EmployeeModel extends BaseModel<AppRole2Employee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app role2 employee model instance should use the {@link AppRole2Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this app role2 employee.
	 *
	 * @return the primary key of this app role2 employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app role2 employee.
	 *
	 * @param primaryKey the primary key of this app role2 employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app role2 employee ID of this app role2 employee.
	 *
	 * @return the app role2 employee ID of this app role2 employee
	 */
	public long getAppRole2EmployeeId();

	/**
	 * Sets the app role2 employee ID of this app role2 employee.
	 *
	 * @param appRole2EmployeeId the app role2 employee ID of this app role2 employee
	 */
	public void setAppRole2EmployeeId(long appRole2EmployeeId);

	/**
	 * Returns the user ID of this app role2 employee.
	 *
	 * @return the user ID of this app role2 employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this app role2 employee.
	 *
	 * @param userId the user ID of this app role2 employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app role2 employee.
	 *
	 * @return the user uuid of this app role2 employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this app role2 employee.
	 *
	 * @param userUuid the user uuid of this app role2 employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this app role2 employee.
	 *
	 * @return the group ID of this app role2 employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this app role2 employee.
	 *
	 * @param groupId the group ID of this app role2 employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this app role2 employee.
	 *
	 * @return the company ID of this app role2 employee
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this app role2 employee.
	 *
	 * @param companyId the company ID of this app role2 employee
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this app role2 employee.
	 *
	 * @return the create date of this app role2 employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this app role2 employee.
	 *
	 * @param createDate the create date of this app role2 employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the app role ID of this app role2 employee.
	 *
	 * @return the app role ID of this app role2 employee
	 */
	public long getAppRoleId();

	/**
	 * Sets the app role ID of this app role2 employee.
	 *
	 * @param appRoleId the app role ID of this app role2 employee
	 */
	public void setAppRoleId(long appRoleId);

	/**
	 * Returns the employee ID of this app role2 employee.
	 *
	 * @return the employee ID of this app role2 employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this app role2 employee.
	 *
	 * @param employeeId the employee ID of this app role2 employee
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppRole2Employee appRole2Employee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppRole2Employee> toCacheModel();

	@Override
	public AppRole2Employee toEscapedModel();

	@Override
	public AppRole2Employee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}