/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierFolder service. Represents a row in the &quot;oep_dossiermgt_dossierfolder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.dossiermgt.model.impl.DossierFolderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.dossiermgt.model.impl.DossierFolderImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierFolder
 * @see org.oep.core.dossiermgt.model.impl.DossierFolderImpl
 * @see org.oep.core.dossiermgt.model.impl.DossierFolderModelImpl
 * @generated
 */
public interface DossierFolderModel extends BaseModel<DossierFolder>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier folder model instance should use the {@link DossierFolder} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier folder.
	 *
	 * @return the primary key of this dossier folder
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier folder.
	 *
	 * @param primaryKey the primary key of this dossier folder
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dossier folder.
	 *
	 * @return the uuid of this dossier folder
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dossier folder.
	 *
	 * @param uuid the uuid of this dossier folder
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the dossier folder ID of this dossier folder.
	 *
	 * @return the dossier folder ID of this dossier folder
	 */
	public long getDossierFolderId();

	/**
	 * Sets the dossier folder ID of this dossier folder.
	 *
	 * @param dossierFolderId the dossier folder ID of this dossier folder
	 */
	public void setDossierFolderId(long dossierFolderId);

	/**
	 * Returns the company ID of this dossier folder.
	 *
	 * @return the company ID of this dossier folder
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier folder.
	 *
	 * @param companyId the company ID of this dossier folder
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this dossier folder.
	 *
	 * @return the create date of this dossier folder
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier folder.
	 *
	 * @param createDate the create date of this dossier folder
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier folder.
	 *
	 * @return the modified date of this dossier folder
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier folder.
	 *
	 * @param modifiedDate the modified date of this dossier folder
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the folder name of this dossier folder.
	 *
	 * @return the folder name of this dossier folder
	 */
	@AutoEscape
	public String getFolderName();

	/**
	 * Sets the folder name of this dossier folder.
	 *
	 * @param folderName the folder name of this dossier folder
	 */
	public void setFolderName(String folderName);

	/**
	 * Returns the parent dossier folder ID of this dossier folder.
	 *
	 * @return the parent dossier folder ID of this dossier folder
	 */
	public long getParentDossierFolderId();

	/**
	 * Sets the parent dossier folder ID of this dossier folder.
	 *
	 * @param parentDossierFolderId the parent dossier folder ID of this dossier folder
	 */
	public void setParentDossierFolderId(long parentDossierFolderId);

	/**
	 * Returns the sequence no of this dossier folder.
	 *
	 * @return the sequence no of this dossier folder
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this dossier folder.
	 *
	 * @param sequenceNo the sequence no of this dossier folder
	 */
	public void setSequenceNo(int sequenceNo);

	/**
	 * Returns the procedure filter of this dossier folder.
	 *
	 * @return the procedure filter of this dossier folder
	 */
	@AutoEscape
	public String getProcedureFilter();

	/**
	 * Sets the procedure filter of this dossier folder.
	 *
	 * @param procedureFilter the procedure filter of this dossier folder
	 */
	public void setProcedureFilter(String procedureFilter);

	/**
	 * Returns the status filter of this dossier folder.
	 *
	 * @return the status filter of this dossier folder
	 */
	@AutoEscape
	public String getStatusFilter();

	/**
	 * Sets the status filter of this dossier folder.
	 *
	 * @param statusFilter the status filter of this dossier folder
	 */
	public void setStatusFilter(String statusFilter);

	/**
	 * Returns the filter by organization of this dossier folder.
	 *
	 * @return the filter by organization of this dossier folder
	 */
	public int getFilterByOrganization();

	/**
	 * Sets the filter by organization of this dossier folder.
	 *
	 * @param filterByOrganization the filter by organization of this dossier folder
	 */
	public void setFilterByOrganization(int filterByOrganization);

	/**
	 * Returns the filter by user of this dossier folder.
	 *
	 * @return the filter by user of this dossier folder
	 */
	public int getFilterByUser();

	/**
	 * Sets the filter by user of this dossier folder.
	 *
	 * @param filterByUser the filter by user of this dossier folder
	 */
	public void setFilterByUser(int filterByUser);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DossierFolder dossierFolder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DossierFolder> toCacheModel();

	@Override
	public DossierFolder toEscapedModel();

	@Override
	public DossierFolder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}