/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentConfig service. Represents a row in the &quot;oep_dossiermgt_PaymentConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.dossiermgt.model.impl.PaymentConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.dossiermgt.model.impl.PaymentConfigImpl}.
 * </p>
 *
 * @author trungdk
 * @see PaymentConfig
 * @see org.oep.core.dossiermgt.model.impl.PaymentConfigImpl
 * @see org.oep.core.dossiermgt.model.impl.PaymentConfigModelImpl
 * @generated
 */
public interface PaymentConfigModel extends BaseModel<PaymentConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment config model instance should use the {@link PaymentConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this payment config.
	 *
	 * @return the primary key of this payment config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment config.
	 *
	 * @param primaryKey the primary key of this payment config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the payment config ID of this payment config.
	 *
	 * @return the payment config ID of this payment config
	 */
	public long getPaymentConfigId();

	/**
	 * Sets the payment config ID of this payment config.
	 *
	 * @param paymentConfigId the payment config ID of this payment config
	 */
	public void setPaymentConfigId(long paymentConfigId);

	/**
	 * Returns the company ID of this payment config.
	 *
	 * @return the company ID of this payment config
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this payment config.
	 *
	 * @param companyId the company ID of this payment config
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this payment config.
	 *
	 * @return the create date of this payment config
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this payment config.
	 *
	 * @param createDate the create date of this payment config
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this payment config.
	 *
	 * @return the modified date of this payment config
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment config.
	 *
	 * @param modifiedDate the modified date of this payment config
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier proc ID of this payment config.
	 *
	 * @return the dossier proc ID of this payment config
	 */
	public long getDossierProcId();

	/**
	 * Sets the dossier proc ID of this payment config.
	 *
	 * @param dossierProcId the dossier proc ID of this payment config
	 */
	public void setDossierProcId(long dossierProcId);

	/**
	 * Returns the gov agent no of this payment config.
	 *
	 * @return the gov agent no of this payment config
	 */
	@AutoEscape
	public String getGovAgentNo();

	/**
	 * Sets the gov agent no of this payment config.
	 *
	 * @param govAgentNo the gov agent no of this payment config
	 */
	public void setGovAgentNo(String govAgentNo);

	/**
	 * Returns the gov agent name of this payment config.
	 *
	 * @return the gov agent name of this payment config
	 */
	@AutoEscape
	public String getGovAgentName();

	/**
	 * Sets the gov agent name of this payment config.
	 *
	 * @param govAgentName the gov agent name of this payment config
	 */
	public void setGovAgentName(String govAgentName);

	/**
	 * Returns the pre paid fee of this payment config.
	 *
	 * @return the pre paid fee of this payment config
	 */
	public long getPrePaidFee();

	/**
	 * Sets the pre paid fee of this payment config.
	 *
	 * @param prePaidFee the pre paid fee of this payment config
	 */
	public void setPrePaidFee(long prePaidFee);

	/**
	 * Returns the bank transfer of this payment config.
	 *
	 * @return the bank transfer of this payment config
	 */
	@AutoEscape
	public String getBankTransfer();

	/**
	 * Sets the bank transfer of this payment config.
	 *
	 * @param bankTransfer the bank transfer of this payment config
	 */
	public void setBankTransfer(String bankTransfer);

	/**
	 * Returns the keypay of this payment config.
	 *
	 * @return the keypay of this payment config
	 */
	@AutoEscape
	public String getKeypay();

	/**
	 * Sets the keypay of this payment config.
	 *
	 * @param keypay the keypay of this payment config
	 */
	public void setKeypay(String keypay);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentConfig paymentConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentConfig> toCacheModel();

	@Override
	public PaymentConfig toEscapedModel();

	@Override
	public PaymentConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}