/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PaymentFile2Dossier service. Represents a row in the &quot;oep_dossiermgt_PaymentFile2Dossier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.dossiermgt.model.impl.PaymentFile2DossierModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.dossiermgt.model.impl.PaymentFile2DossierImpl}.
 * </p>
 *
 * @author trungdk
 * @see PaymentFile2Dossier
 * @see org.oep.core.dossiermgt.model.impl.PaymentFile2DossierImpl
 * @see org.oep.core.dossiermgt.model.impl.PaymentFile2DossierModelImpl
 * @generated
 */
public interface PaymentFile2DossierModel extends BaseModel<PaymentFile2Dossier> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment file2 dossier model instance should use the {@link PaymentFile2Dossier} interface instead.
	 */

	/**
	 * Returns the primary key of this payment file2 dossier.
	 *
	 * @return the primary key of this payment file2 dossier
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment file2 dossier.
	 *
	 * @param primaryKey the primary key of this payment file2 dossier
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this payment file2 dossier.
	 *
	 * @return the ID of this payment file2 dossier
	 */
	public long getId();

	/**
	 * Sets the ID of this payment file2 dossier.
	 *
	 * @param id the ID of this payment file2 dossier
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this payment file2 dossier.
	 *
	 * @return the company ID of this payment file2 dossier
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this payment file2 dossier.
	 *
	 * @param companyId the company ID of this payment file2 dossier
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the payment file ID of this payment file2 dossier.
	 *
	 * @return the payment file ID of this payment file2 dossier
	 */
	public long getPaymentFileId();

	/**
	 * Sets the payment file ID of this payment file2 dossier.
	 *
	 * @param paymentFileId the payment file ID of this payment file2 dossier
	 */
	public void setPaymentFileId(long paymentFileId);

	/**
	 * Returns the dossier ID of this payment file2 dossier.
	 *
	 * @return the dossier ID of this payment file2 dossier
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this payment file2 dossier.
	 *
	 * @param dossierId the dossier ID of this payment file2 dossier
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the amount of this payment file2 dossier.
	 *
	 * @return the amount of this payment file2 dossier
	 */
	public long getAmount();

	/**
	 * Sets the amount of this payment file2 dossier.
	 *
	 * @param amount the amount of this payment file2 dossier
	 */
	public void setAmount(long amount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentFile2Dossier paymentFile2Dossier);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentFile2Dossier> toCacheModel();

	@Override
	public PaymentFile2Dossier toEscapedModel();

	@Override
	public PaymentFile2Dossier toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}