/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentFile service. Represents a row in the &quot;oep_dossiermgt_PaymentFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.dossiermgt.model.impl.PaymentFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.dossiermgt.model.impl.PaymentFileImpl}.
 * </p>
 *
 * @author trungdk
 * @see PaymentFile
 * @see org.oep.core.dossiermgt.model.impl.PaymentFileImpl
 * @see org.oep.core.dossiermgt.model.impl.PaymentFileModelImpl
 * @generated
 */
public interface PaymentFileModel extends BaseModel<PaymentFile>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment file model instance should use the {@link PaymentFile} interface instead.
	 */

	/**
	 * Returns the primary key of this payment file.
	 *
	 * @return the primary key of this payment file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment file.
	 *
	 * @param primaryKey the primary key of this payment file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this payment file.
	 *
	 * @return the uuid of this payment file
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this payment file.
	 *
	 * @param uuid the uuid of this payment file
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the payment file ID of this payment file.
	 *
	 * @return the payment file ID of this payment file
	 */
	public long getPaymentFileId();

	/**
	 * Sets the payment file ID of this payment file.
	 *
	 * @param paymentFileId the payment file ID of this payment file
	 */
	public void setPaymentFileId(long paymentFileId);

	/**
	 * Returns the user ID of this payment file.
	 *
	 * @return the user ID of this payment file
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this payment file.
	 *
	 * @param userId the user ID of this payment file
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this payment file.
	 *
	 * @return the user uuid of this payment file
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this payment file.
	 *
	 * @param userUuid the user uuid of this payment file
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this payment file.
	 *
	 * @return the group ID of this payment file
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this payment file.
	 *
	 * @param groupId the group ID of this payment file
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this payment file.
	 *
	 * @return the company ID of this payment file
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this payment file.
	 *
	 * @param companyId the company ID of this payment file
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this payment file.
	 *
	 * @return the create date of this payment file
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this payment file.
	 *
	 * @param createDate the create date of this payment file
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this payment file.
	 *
	 * @return the modified date of this payment file
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment file.
	 *
	 * @param modifiedDate the modified date of this payment file
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this payment file.
	 *
	 * @return the organization ID of this payment file
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this payment file.
	 *
	 * @param organizationId the organization ID of this payment file
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the amount of this payment file.
	 *
	 * @return the amount of this payment file
	 */
	public long getAmount();

	/**
	 * Sets the amount of this payment file.
	 *
	 * @param amount the amount of this payment file
	 */
	public void setAmount(long amount);

	/**
	 * Returns the payment type of this payment file.
	 *
	 * @return the payment type of this payment file
	 */
	public int getPaymentType();

	/**
	 * Sets the payment type of this payment file.
	 *
	 * @param paymentType the payment type of this payment file
	 */
	public void setPaymentType(int paymentType);

	/**
	 * Returns the detail info of this payment file.
	 *
	 * @return the detail info of this payment file
	 */
	@AutoEscape
	public String getDetailInfo();

	/**
	 * Sets the detail info of this payment file.
	 *
	 * @param detailInfo the detail info of this payment file
	 */
	public void setDetailInfo(String detailInfo);

	/**
	 * Returns the note of this payment file.
	 *
	 * @return the note of this payment file
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this payment file.
	 *
	 * @param note the note of this payment file
	 */
	public void setNote(String note);

	/**
	 * Returns the file entry ID of this payment file.
	 *
	 * @return the file entry ID of this payment file
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this payment file.
	 *
	 * @param fileEntryId the file entry ID of this payment file
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the issue date of this payment file.
	 *
	 * @return the issue date of this payment file
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this payment file.
	 *
	 * @param issueDate the issue date of this payment file
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the checking date of this payment file.
	 *
	 * @return the checking date of this payment file
	 */
	public Date getCheckingDate();

	/**
	 * Sets the checking date of this payment file.
	 *
	 * @param checkingDate the checking date of this payment file
	 */
	public void setCheckingDate(Date checkingDate);

	/**
	 * Returns the checking user ID of this payment file.
	 *
	 * @return the checking user ID of this payment file
	 */
	public long getCheckingUserId();

	/**
	 * Sets the checking user ID of this payment file.
	 *
	 * @param checkingUserId the checking user ID of this payment file
	 */
	public void setCheckingUserId(long checkingUserId);

	/**
	 * Returns the checking user uuid of this payment file.
	 *
	 * @return the checking user uuid of this payment file
	 * @throws SystemException if a system exception occurred
	 */
	public String getCheckingUserUuid() throws SystemException;

	/**
	 * Sets the checking user uuid of this payment file.
	 *
	 * @param checkingUserUuid the checking user uuid of this payment file
	 */
	public void setCheckingUserUuid(String checkingUserUuid);

	/**
	 * Returns the checking user name of this payment file.
	 *
	 * @return the checking user name of this payment file
	 */
	@AutoEscape
	public String getCheckingUserName();

	/**
	 * Sets the checking user name of this payment file.
	 *
	 * @param checkingUserName the checking user name of this payment file
	 */
	public void setCheckingUserName(String checkingUserName);

	/**
	 * Returns the checking result of this payment file.
	 *
	 * @return the checking result of this payment file
	 */
	public int getCheckingResult();

	/**
	 * Sets the checking result of this payment file.
	 *
	 * @param checkingResult the checking result of this payment file
	 */
	public void setCheckingResult(int checkingResult);

	/**
	 * Returns the checking note of this payment file.
	 *
	 * @return the checking note of this payment file
	 */
	@AutoEscape
	public String getCheckingNote();

	/**
	 * Sets the checking note of this payment file.
	 *
	 * @param checkingNote the checking note of this payment file
	 */
	public void setCheckingNote(String checkingNote);

	/**
	 * Returns the feedback date of this payment file.
	 *
	 * @return the feedback date of this payment file
	 */
	public Date getFeedbackDate();

	/**
	 * Sets the feedback date of this payment file.
	 *
	 * @param feedbackDate the feedback date of this payment file
	 */
	public void setFeedbackDate(Date feedbackDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PaymentFile paymentFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PaymentFile> toCacheModel();

	@Override
	public PaymentFile toEscapedModel();

	@Override
	public PaymentFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}