/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.usermgt.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Delegacy service. Represents a row in the &quot;oep_usermgt_delegacy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.usermgt.model.impl.DelegacyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.usermgt.model.impl.DelegacyImpl}.
 * </p>
 *
 * @author NQMINH
 * @see Delegacy
 * @see org.oep.usermgt.model.impl.DelegacyImpl
 * @see org.oep.usermgt.model.impl.DelegacyModelImpl
 * @generated
 */
public interface DelegacyModel extends BaseModel<Delegacy> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a delegacy model instance should use the {@link Delegacy} interface instead.
	 */

	/**
	 * Returns the primary key of this delegacy.
	 *
	 * @return the primary key of this delegacy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this delegacy.
	 *
	 * @param primaryKey the primary key of this delegacy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the delegacy ID of this delegacy.
	 *
	 * @return the delegacy ID of this delegacy
	 */
	public long getDelegacyId();

	/**
	 * Sets the delegacy ID of this delegacy.
	 *
	 * @param delegacyId the delegacy ID of this delegacy
	 */
	public void setDelegacyId(long delegacyId);

	/**
	 * Returns the company ID of this delegacy.
	 *
	 * @return the company ID of this delegacy
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this delegacy.
	 *
	 * @param companyId the company ID of this delegacy
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this delegacy.
	 *
	 * @return the group ID of this delegacy
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this delegacy.
	 *
	 * @param groupId the group ID of this delegacy
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this delegacy.
	 *
	 * @return the user ID of this delegacy
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this delegacy.
	 *
	 * @param userId the user ID of this delegacy
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this delegacy.
	 *
	 * @return the user uuid of this delegacy
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this delegacy.
	 *
	 * @param userUuid the user uuid of this delegacy
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this delegacy.
	 *
	 * @return the create date of this delegacy
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this delegacy.
	 *
	 * @param createDate the create date of this delegacy
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the from employee ID of this delegacy.
	 *
	 * @return the from employee ID of this delegacy
	 */
	public long getFromEmployeeId();

	/**
	 * Sets the from employee ID of this delegacy.
	 *
	 * @param fromEmployeeId the from employee ID of this delegacy
	 */
	public void setFromEmployeeId(long fromEmployeeId);

	/**
	 * Returns the to employee ID of this delegacy.
	 *
	 * @return the to employee ID of this delegacy
	 */
	public long getToEmployeeId();

	/**
	 * Sets the to employee ID of this delegacy.
	 *
	 * @param toEmployeeId the to employee ID of this delegacy
	 */
	public void setToEmployeeId(long toEmployeeId);

	/**
	 * Returns the role ID of this delegacy.
	 *
	 * @return the role ID of this delegacy
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this delegacy.
	 *
	 * @param roleId the role ID of this delegacy
	 */
	public void setRoleId(long roleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Delegacy delegacy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Delegacy> toCacheModel();

	@Override
	public Delegacy toEscapedModel();

	@Override
	public Delegacy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}