/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.usermgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.oep.usermgt.service.persistence.JobPos2RolePK;

import java.io.Serializable;

/**
 * The base model interface for the JobPos2Role service. Represents a row in the &quot;oep_usermgt_jobpos2role&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.usermgt.model.impl.JobPos2RoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.usermgt.model.impl.JobPos2RoleImpl}.
 * </p>
 *
 * @author NQMINH
 * @see JobPos2Role
 * @see org.oep.usermgt.model.impl.JobPos2RoleImpl
 * @see org.oep.usermgt.model.impl.JobPos2RoleModelImpl
 * @generated
 */
public interface JobPos2RoleModel extends BaseModel<JobPos2Role> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jobpos to role model instance should use the {@link JobPos2Role} interface instead.
	 */

	/**
	 * Returns the primary key of this jobpos to role.
	 *
	 * @return the primary key of this jobpos to role
	 */
	public JobPos2RolePK getPrimaryKey();

	/**
	 * Sets the primary key of this jobpos to role.
	 *
	 * @param primaryKey the primary key of this jobpos to role
	 */
	public void setPrimaryKey(JobPos2RolePK primaryKey);

	/**
	 * Returns the job pos ID of this jobpos to role.
	 *
	 * @return the job pos ID of this jobpos to role
	 */
	public long getJobPosId();

	/**
	 * Sets the job pos ID of this jobpos to role.
	 *
	 * @param jobPosId the job pos ID of this jobpos to role
	 */
	public void setJobPosId(long jobPosId);

	/**
	 * Returns the role ID of this jobpos to role.
	 *
	 * @return the role ID of this jobpos to role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this jobpos to role.
	 *
	 * @param roleId the role ID of this jobpos to role
	 */
	public void setRoleId(long roleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobPos2Role jobPos2Role);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobPos2Role> toCacheModel();

	@Override
	public JobPos2Role toEscapedModel();

	@Override
	public JobPos2Role toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}