/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.usermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkingUnit service. Represents a row in the &quot;oep_usermgt_workingunit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.usermgt.model.impl.WorkingUnitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.usermgt.model.impl.WorkingUnitImpl}.
 * </p>
 *
 * @author NQMINH
 * @see WorkingUnit
 * @see org.oep.usermgt.model.impl.WorkingUnitImpl
 * @see org.oep.usermgt.model.impl.WorkingUnitModelImpl
 * @generated
 */
public interface WorkingUnitModel extends BaseModel<WorkingUnit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Working Unit model instance should use the {@link WorkingUnit} interface instead.
	 */

	/**
	 * Returns the primary key of this Working Unit.
	 *
	 * @return the primary key of this Working Unit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Working Unit.
	 *
	 * @param primaryKey the primary key of this Working Unit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the working unit ID of this Working Unit.
	 *
	 * @return the working unit ID of this Working Unit
	 */
	public long getWorkingUnitId();

	/**
	 * Sets the working unit ID of this Working Unit.
	 *
	 * @param workingUnitId the working unit ID of this Working Unit
	 */
	public void setWorkingUnitId(long workingUnitId);

	/**
	 * Returns the company ID of this Working Unit.
	 *
	 * @return the company ID of this Working Unit
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this Working Unit.
	 *
	 * @param companyId the company ID of this Working Unit
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this Working Unit.
	 *
	 * @return the group ID of this Working Unit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Working Unit.
	 *
	 * @param groupId the group ID of this Working Unit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this Working Unit.
	 *
	 * @return the user ID of this Working Unit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Working Unit.
	 *
	 * @param userId the user ID of this Working Unit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Working Unit.
	 *
	 * @return the user uuid of this Working Unit
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Working Unit.
	 *
	 * @param userUuid the user uuid of this Working Unit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this Working Unit.
	 *
	 * @return the create date of this Working Unit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Working Unit.
	 *
	 * @param createDate the create date of this Working Unit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Working Unit.
	 *
	 * @return the modified date of this Working Unit
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Working Unit.
	 *
	 * @param modifiedDate the modified date of this Working Unit
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this Working Unit.
	 *
	 * @return the organization ID of this Working Unit
	 */
	@AutoEscape
	public String getOrganizationId();

	/**
	 * Sets the organization ID of this Working Unit.
	 *
	 * @param organizationId the organization ID of this Working Unit
	 */
	public void setOrganizationId(String organizationId);

	/**
	 * Returns the gov agency ID of this Working Unit.
	 *
	 * @return the gov agency ID of this Working Unit
	 */
	@AutoEscape
	public String getGovAgencyId();

	/**
	 * Sets the gov agency ID of this Working Unit.
	 *
	 * @param govAgencyId the gov agency ID of this Working Unit
	 */
	public void setGovAgencyId(String govAgencyId);

	/**
	 * Returns the name of this Working Unit.
	 *
	 * @return the name of this Working Unit
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this Working Unit.
	 *
	 * @param name the name of this Working Unit
	 */
	public void setName(String name);

	/**
	 * Returns the en name of this Working Unit.
	 *
	 * @return the en name of this Working Unit
	 */
	@AutoEscape
	public String getEnName();

	/**
	 * Sets the en name of this Working Unit.
	 *
	 * @param enName the en name of this Working Unit
	 */
	public void setEnName(String enName);

	/**
	 * Returns the parent working unit ID of this Working Unit.
	 *
	 * @return the parent working unit ID of this Working Unit
	 */
	public long getParentWorkingUnitId();

	/**
	 * Sets the parent working unit ID of this Working Unit.
	 *
	 * @param parentWorkingUnitId the parent working unit ID of this Working Unit
	 */
	public void setParentWorkingUnitId(long parentWorkingUnitId);

	/**
	 * Returns the address of this Working Unit.
	 *
	 * @return the address of this Working Unit
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this Working Unit.
	 *
	 * @param address the address of this Working Unit
	 */
	public void setAddress(String address);

	/**
	 * Returns the city no of this Working Unit.
	 *
	 * @return the city no of this Working Unit
	 */
	@AutoEscape
	public String getCityNo();

	/**
	 * Sets the city no of this Working Unit.
	 *
	 * @param cityNo the city no of this Working Unit
	 */
	public void setCityNo(String cityNo);

	/**
	 * Returns the city name of this Working Unit.
	 *
	 * @return the city name of this Working Unit
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this Working Unit.
	 *
	 * @param cityName the city name of this Working Unit
	 */
	public void setCityName(String cityName);

	/**
	 * Returns the district no of this Working Unit.
	 *
	 * @return the district no of this Working Unit
	 */
	@AutoEscape
	public String getDistrictNo();

	/**
	 * Sets the district no of this Working Unit.
	 *
	 * @param districtNo the district no of this Working Unit
	 */
	public void setDistrictNo(String districtNo);

	/**
	 * Returns the district name of this Working Unit.
	 *
	 * @return the district name of this Working Unit
	 */
	@AutoEscape
	public String getDistrictName();

	/**
	 * Sets the district name of this Working Unit.
	 *
	 * @param districtName the district name of this Working Unit
	 */
	public void setDistrictName(String districtName);

	/**
	 * Returns the ward no of this Working Unit.
	 *
	 * @return the ward no of this Working Unit
	 */
	@AutoEscape
	public String getWardNo();

	/**
	 * Sets the ward no of this Working Unit.
	 *
	 * @param wardNo the ward no of this Working Unit
	 */
	public void setWardNo(String wardNo);

	/**
	 * Returns the ward name of this Working Unit.
	 *
	 * @return the ward name of this Working Unit
	 */
	@AutoEscape
	public String getWardName();

	/**
	 * Sets the ward name of this Working Unit.
	 *
	 * @param wardName the ward name of this Working Unit
	 */
	public void setWardName(String wardName);

	/**
	 * Returns the gps position of this Working Unit.
	 *
	 * @return the gps position of this Working Unit
	 */
	@AutoEscape
	public String getGpsPosition();

	/**
	 * Sets the gps position of this Working Unit.
	 *
	 * @param gpsPosition the gps position of this Working Unit
	 */
	public void setGpsPosition(String gpsPosition);

	/**
	 * Returns the tel no of this Working Unit.
	 *
	 * @return the tel no of this Working Unit
	 */
	@AutoEscape
	public String getTelNo();

	/**
	 * Sets the tel no of this Working Unit.
	 *
	 * @param telNo the tel no of this Working Unit
	 */
	public void setTelNo(String telNo);

	/**
	 * Returns the fax of this Working Unit.
	 *
	 * @return the fax of this Working Unit
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this Working Unit.
	 *
	 * @param fax the fax of this Working Unit
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this Working Unit.
	 *
	 * @return the email of this Working Unit
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this Working Unit.
	 *
	 * @param email the email of this Working Unit
	 */
	public void setEmail(String email);

	/**
	 * Returns the website of this Working Unit.
	 *
	 * @return the website of this Working Unit
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this Working Unit.
	 *
	 * @param website the website of this Working Unit
	 */
	public void setWebsite(String website);

	/**
	 * Returns the aaa of this Working Unit.
	 *
	 * @return the aaa of this Working Unit
	 */
	@AutoEscape
	public String getAaa();

	/**
	 * Sets the aaa of this Working Unit.
	 *
	 * @param aaa the aaa of this Working Unit
	 */
	public void setAaa(String aaa);

	/**
	 * Returns the short name of this Working Unit.
	 *
	 * @return the short name of this Working Unit
	 */
	@AutoEscape
	public String getShortName();

	/**
	 * Sets the short name of this Working Unit.
	 *
	 * @param shortName the short name of this Working Unit
	 */
	public void setShortName(String shortName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkingUnit workingUnit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkingUnit> toCacheModel();

	@Override
	public WorkingUnit toEscapedModel();

	@Override
	public WorkingUnit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}