/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.ssomgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppRole service. Represents a row in the &quot;oep_ssomgt_approle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.ssomgt.model.impl.AppRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.ssomgt.model.impl.AppRoleImpl}.
 * </p>
 *
 * @author trungdk
 * @see AppRole
 * @see org.oep.ssomgt.model.impl.AppRoleImpl
 * @see org.oep.ssomgt.model.impl.AppRoleModelImpl
 * @generated
 */
public interface AppRoleModel extends BaseModel<AppRole> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app role model instance should use the {@link AppRole} interface instead.
	 */

	/**
	 * Returns the primary key of this app role.
	 *
	 * @return the primary key of this app role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app role.
	 *
	 * @param primaryKey the primary key of this app role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app role ID of this app role.
	 *
	 * @return the app role ID of this app role
	 */
	public long getAppRoleId();

	/**
	 * Sets the app role ID of this app role.
	 *
	 * @param appRoleId the app role ID of this app role
	 */
	public void setAppRoleId(long appRoleId);

	/**
	 * Returns the user ID of this app role.
	 *
	 * @return the user ID of this app role
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this app role.
	 *
	 * @param userId the user ID of this app role
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app role.
	 *
	 * @return the user uuid of this app role
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this app role.
	 *
	 * @param userUuid the user uuid of this app role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this app role.
	 *
	 * @return the group ID of this app role
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this app role.
	 *
	 * @param groupId the group ID of this app role
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this app role.
	 *
	 * @return the company ID of this app role
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this app role.
	 *
	 * @param companyId the company ID of this app role
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this app role.
	 *
	 * @return the create date of this app role
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this app role.
	 *
	 * @param createDate the create date of this app role
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the application ID of this app role.
	 *
	 * @return the application ID of this app role
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this app role.
	 *
	 * @param applicationId the application ID of this app role
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the role code of this app role.
	 *
	 * @return the role code of this app role
	 */
	@AutoEscape
	public String getRoleCode();

	/**
	 * Sets the role code of this app role.
	 *
	 * @param roleCode the role code of this app role
	 */
	public void setRoleCode(String roleCode);

	/**
	 * Returns the role name of this app role.
	 *
	 * @return the role name of this app role
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this app role.
	 *
	 * @param roleName the role name of this app role
	 */
	public void setRoleName(String roleName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AppRole appRole);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AppRole> toCacheModel();

	@Override
	public AppRole toEscapedModel();

	@Override
	public AppRole toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}