/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.ssomgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserSync service. Represents a row in the &quot;oep_usermgt_usersync&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.ssomgt.model.impl.UserSyncModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.ssomgt.model.impl.UserSyncImpl}.
 * </p>
 *
 * @author trungdk
 * @see UserSync
 * @see org.oep.ssomgt.model.impl.UserSyncImpl
 * @see org.oep.ssomgt.model.impl.UserSyncModelImpl
 * @generated
 */
public interface UserSyncModel extends BaseModel<UserSync> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user sync model instance should use the {@link UserSync} interface instead.
	 */

	/**
	 * Returns the primary key of this user sync.
	 *
	 * @return the primary key of this user sync
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user sync.
	 *
	 * @param primaryKey the primary key of this user sync
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user sync ID of this user sync.
	 *
	 * @return the user sync ID of this user sync
	 */
	public long getUserSyncId();

	/**
	 * Sets the user sync ID of this user sync.
	 *
	 * @param userSyncId the user sync ID of this user sync
	 */
	public void setUserSyncId(long userSyncId);

	/**
	 * Returns the application ID of this user sync.
	 *
	 * @return the application ID of this user sync
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this user sync.
	 *
	 * @param applicationId the application ID of this user sync
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the employee ID of this user sync.
	 *
	 * @return the employee ID of this user sync
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this user sync.
	 *
	 * @param employeeId the employee ID of this user sync
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the user ID of this user sync.
	 *
	 * @return the user ID of this user sync
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user sync.
	 *
	 * @param userId the user ID of this user sync
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user sync.
	 *
	 * @return the user uuid of this user sync
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user sync.
	 *
	 * @param userUuid the user uuid of this user sync
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the sso user name of this user sync.
	 *
	 * @return the sso user name of this user sync
	 */
	@AutoEscape
	public String getSsoUserName();

	/**
	 * Sets the sso user name of this user sync.
	 *
	 * @param ssoUserName the sso user name of this user sync
	 */
	public void setSsoUserName(String ssoUserName);

	/**
	 * Returns the app user name of this user sync.
	 *
	 * @return the app user name of this user sync
	 */
	@AutoEscape
	public String getAppUserName();

	/**
	 * Sets the app user name of this user sync.
	 *
	 * @param appUserName the app user name of this user sync
	 */
	public void setAppUserName(String appUserName);

	/**
	 * Returns the full name of this user sync.
	 *
	 * @return the full name of this user sync
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this user sync.
	 *
	 * @param fullName the full name of this user sync
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the email of this user sync.
	 *
	 * @return the email of this user sync
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user sync.
	 *
	 * @param email the email of this user sync
	 */
	public void setEmail(String email);

	/**
	 * Returns the password of this user sync.
	 *
	 * @return the password of this user sync
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this user sync.
	 *
	 * @param password the password of this user sync
	 */
	public void setPassword(String password);

	/**
	 * Returns the accessible status of this user sync.
	 *
	 * @return the accessible status of this user sync
	 */
	public int getAccessibleStatus();

	/**
	 * Sets the accessible status of this user sync.
	 *
	 * @param accessibleStatus the accessible status of this user sync
	 */
	public void setAccessibleStatus(int accessibleStatus);

	/**
	 * Returns the roles of this user sync.
	 *
	 * @return the roles of this user sync
	 */
	@AutoEscape
	public String getRoles();

	/**
	 * Sets the roles of this user sync.
	 *
	 * @param roles the roles of this user sync
	 */
	public void setRoles(String roles);

	/**
	 * Returns the checkpoint of this user sync.
	 *
	 * @return the checkpoint of this user sync
	 */
	public Date getCheckpoint();

	/**
	 * Sets the checkpoint of this user sync.
	 *
	 * @param checkpoint the checkpoint of this user sync
	 */
	public void setCheckpoint(Date checkpoint);

	/**
	 * Returns the sync time of this user sync.
	 *
	 * @return the sync time of this user sync
	 */
	public Date getSyncTime();

	/**
	 * Sets the sync time of this user sync.
	 *
	 * @param syncTime the sync time of this user sync
	 */
	public void setSyncTime(Date syncTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserSync userSync);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserSync> toCacheModel();

	@Override
	public UserSync toEscapedModel();

	@Override
	public UserSync toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}