/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.processmgt.model.ProcessOrder;
import org.oep.core.processmgt.model.ProcessOrderModel;
import org.oep.core.processmgt.model.ProcessOrderSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ProcessOrder service. Represents a row in the &quot;oep_processmgt_processorder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.processmgt.model.ProcessOrderModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProcessOrderImpl}.
 * </p>
 *
 * @author trungdk
 * @see ProcessOrderImpl
 * @see org.oep.core.processmgt.model.ProcessOrder
 * @see org.oep.core.processmgt.model.ProcessOrderModel
 * @generated
 */
@JSON(strict = true)
public class ProcessOrderModelImpl extends BaseModelImpl<ProcessOrder>
	implements ProcessOrderModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a process order model instance should use the {@link org.oep.core.processmgt.model.ProcessOrder} interface instead.
	 */
	public static final String TABLE_NAME = "oep_processmgt_processorder";
	public static final Object[][] TABLE_COLUMNS = {
			{ "processOrderId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "organizationId", Types.BIGINT },
			{ "parentProcessOrderId", Types.BIGINT },
			{ "dossierId", Types.BIGINT },
			{ "dossierProcessId", Types.BIGINT },
			{ "dossierStepId", Types.BIGINT },
			{ "dossierStatus", Types.VARCHAR },
			{ "dossierResume", Types.VARCHAR },
			{ "stepDate", Types.TIMESTAMP },
			{ "stepNote", Types.VARCHAR },
			{ "assignToUserId", Types.BIGINT },
			{ "currentCondition", Types.VARCHAR },
			{ "endState", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_processmgt_processorder (processOrderId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,organizationId LONG,parentProcessOrderId LONG,dossierId LONG,dossierProcessId LONG,dossierStepId LONG,dossierStatus VARCHAR(75) null,dossierResume VARCHAR(75) null,stepDate DATE null,stepNote VARCHAR(75) null,assignToUserId LONG,currentCondition VARCHAR(75) null,endState INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table oep_processmgt_processorder";
	public static final String ORDER_BY_JPQL = " ORDER BY processOrder.processOrderId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_processmgt_processorder.processOrderId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.processmgt.model.ProcessOrder"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.processmgt.model.ProcessOrder"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProcessOrder toModel(ProcessOrderSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProcessOrder model = new ProcessOrderImpl();

		model.setProcessOrderId(soapModel.getProcessOrderId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setParentProcessOrderId(soapModel.getParentProcessOrderId());
		model.setDossierId(soapModel.getDossierId());
		model.setDossierProcessId(soapModel.getDossierProcessId());
		model.setDossierStepId(soapModel.getDossierStepId());
		model.setDossierStatus(soapModel.getDossierStatus());
		model.setDossierResume(soapModel.getDossierResume());
		model.setStepDate(soapModel.getStepDate());
		model.setStepNote(soapModel.getStepNote());
		model.setAssignToUserId(soapModel.getAssignToUserId());
		model.setCurrentCondition(soapModel.getCurrentCondition());
		model.setEndState(soapModel.getEndState());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProcessOrder> toModels(ProcessOrderSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ProcessOrder> models = new ArrayList<ProcessOrder>(soapModels.length);

		for (ProcessOrderSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.processmgt.model.ProcessOrder"));

	public ProcessOrderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _processOrderId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProcessOrderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _processOrderId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProcessOrder.class;
	}

	@Override
	public String getModelClassName() {
		return ProcessOrder.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("processOrderId", getProcessOrderId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("parentProcessOrderId", getParentProcessOrderId());
		attributes.put("dossierId", getDossierId());
		attributes.put("dossierProcessId", getDossierProcessId());
		attributes.put("dossierStepId", getDossierStepId());
		attributes.put("dossierStatus", getDossierStatus());
		attributes.put("dossierResume", getDossierResume());
		attributes.put("stepDate", getStepDate());
		attributes.put("stepNote", getStepNote());
		attributes.put("assignToUserId", getAssignToUserId());
		attributes.put("currentCondition", getCurrentCondition());
		attributes.put("endState", getEndState());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long processOrderId = (Long)attributes.get("processOrderId");

		if (processOrderId != null) {
			setProcessOrderId(processOrderId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		Long parentProcessOrderId = (Long)attributes.get("parentProcessOrderId");

		if (parentProcessOrderId != null) {
			setParentProcessOrderId(parentProcessOrderId);
		}

		Long dossierId = (Long)attributes.get("dossierId");

		if (dossierId != null) {
			setDossierId(dossierId);
		}

		Long dossierProcessId = (Long)attributes.get("dossierProcessId");

		if (dossierProcessId != null) {
			setDossierProcessId(dossierProcessId);
		}

		Long dossierStepId = (Long)attributes.get("dossierStepId");

		if (dossierStepId != null) {
			setDossierStepId(dossierStepId);
		}

		String dossierStatus = (String)attributes.get("dossierStatus");

		if (dossierStatus != null) {
			setDossierStatus(dossierStatus);
		}

		String dossierResume = (String)attributes.get("dossierResume");

		if (dossierResume != null) {
			setDossierResume(dossierResume);
		}

		Date stepDate = (Date)attributes.get("stepDate");

		if (stepDate != null) {
			setStepDate(stepDate);
		}

		String stepNote = (String)attributes.get("stepNote");

		if (stepNote != null) {
			setStepNote(stepNote);
		}

		Long assignToUserId = (Long)attributes.get("assignToUserId");

		if (assignToUserId != null) {
			setAssignToUserId(assignToUserId);
		}

		String currentCondition = (String)attributes.get("currentCondition");

		if (currentCondition != null) {
			setCurrentCondition(currentCondition);
		}

		Integer endState = (Integer)attributes.get("endState");

		if (endState != null) {
			setEndState(endState);
		}
	}

	@JSON
	@Override
	public long getProcessOrderId() {
		return _processOrderId;
	}

	@Override
	public void setProcessOrderId(long processOrderId) {
		_processOrderId = processOrderId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_organizationId = organizationId;
	}

	@JSON
	@Override
	public long getParentProcessOrderId() {
		return _parentProcessOrderId;
	}

	@Override
	public void setParentProcessOrderId(long parentProcessOrderId) {
		_parentProcessOrderId = parentProcessOrderId;
	}

	@JSON
	@Override
	public long getDossierId() {
		return _dossierId;
	}

	@Override
	public void setDossierId(long dossierId) {
		_dossierId = dossierId;
	}

	@JSON
	@Override
	public long getDossierProcessId() {
		return _dossierProcessId;
	}

	@Override
	public void setDossierProcessId(long dossierProcessId) {
		_dossierProcessId = dossierProcessId;
	}

	@JSON
	@Override
	public long getDossierStepId() {
		return _dossierStepId;
	}

	@Override
	public void setDossierStepId(long dossierStepId) {
		_dossierStepId = dossierStepId;
	}

	@JSON
	@Override
	public String getDossierStatus() {
		if (_dossierStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierStatus;
		}
	}

	@Override
	public void setDossierStatus(String dossierStatus) {
		_dossierStatus = dossierStatus;
	}

	@JSON
	@Override
	public String getDossierResume() {
		if (_dossierResume == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierResume;
		}
	}

	@Override
	public void setDossierResume(String dossierResume) {
		_dossierResume = dossierResume;
	}

	@JSON
	@Override
	public Date getStepDate() {
		return _stepDate;
	}

	@Override
	public void setStepDate(Date stepDate) {
		_stepDate = stepDate;
	}

	@JSON
	@Override
	public String getStepNote() {
		if (_stepNote == null) {
			return StringPool.BLANK;
		}
		else {
			return _stepNote;
		}
	}

	@Override
	public void setStepNote(String stepNote) {
		_stepNote = stepNote;
	}

	@JSON
	@Override
	public long getAssignToUserId() {
		return _assignToUserId;
	}

	@Override
	public void setAssignToUserId(long assignToUserId) {
		_assignToUserId = assignToUserId;
	}

	@Override
	public String getAssignToUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getAssignToUserId(), "uuid",
			_assignToUserUuid);
	}

	@Override
	public void setAssignToUserUuid(String assignToUserUuid) {
		_assignToUserUuid = assignToUserUuid;
	}

	@JSON
	@Override
	public String getCurrentCondition() {
		if (_currentCondition == null) {
			return StringPool.BLANK;
		}
		else {
			return _currentCondition;
		}
	}

	@Override
	public void setCurrentCondition(String currentCondition) {
		_currentCondition = currentCondition;
	}

	@JSON
	@Override
	public int getEndState() {
		return _endState;
	}

	@Override
	public void setEndState(int endState) {
		_endState = endState;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ProcessOrder.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProcessOrder toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ProcessOrder)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProcessOrderImpl processOrderImpl = new ProcessOrderImpl();

		processOrderImpl.setProcessOrderId(getProcessOrderId());
		processOrderImpl.setUserId(getUserId());
		processOrderImpl.setGroupId(getGroupId());
		processOrderImpl.setCompanyId(getCompanyId());
		processOrderImpl.setCreateDate(getCreateDate());
		processOrderImpl.setModifiedDate(getModifiedDate());
		processOrderImpl.setOrganizationId(getOrganizationId());
		processOrderImpl.setParentProcessOrderId(getParentProcessOrderId());
		processOrderImpl.setDossierId(getDossierId());
		processOrderImpl.setDossierProcessId(getDossierProcessId());
		processOrderImpl.setDossierStepId(getDossierStepId());
		processOrderImpl.setDossierStatus(getDossierStatus());
		processOrderImpl.setDossierResume(getDossierResume());
		processOrderImpl.setStepDate(getStepDate());
		processOrderImpl.setStepNote(getStepNote());
		processOrderImpl.setAssignToUserId(getAssignToUserId());
		processOrderImpl.setCurrentCondition(getCurrentCondition());
		processOrderImpl.setEndState(getEndState());

		processOrderImpl.resetOriginalValues();

		return processOrderImpl;
	}

	@Override
	public int compareTo(ProcessOrder processOrder) {
		long primaryKey = processOrder.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProcessOrder)) {
			return false;
		}

		ProcessOrder processOrder = (ProcessOrder)obj;

		long primaryKey = processOrder.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ProcessOrder> toCacheModel() {
		ProcessOrderCacheModel processOrderCacheModel = new ProcessOrderCacheModel();

		processOrderCacheModel.processOrderId = getProcessOrderId();

		processOrderCacheModel.userId = getUserId();

		processOrderCacheModel.groupId = getGroupId();

		processOrderCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			processOrderCacheModel.createDate = createDate.getTime();
		}
		else {
			processOrderCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			processOrderCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			processOrderCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		processOrderCacheModel.organizationId = getOrganizationId();

		processOrderCacheModel.parentProcessOrderId = getParentProcessOrderId();

		processOrderCacheModel.dossierId = getDossierId();

		processOrderCacheModel.dossierProcessId = getDossierProcessId();

		processOrderCacheModel.dossierStepId = getDossierStepId();

		processOrderCacheModel.dossierStatus = getDossierStatus();

		String dossierStatus = processOrderCacheModel.dossierStatus;

		if ((dossierStatus != null) && (dossierStatus.length() == 0)) {
			processOrderCacheModel.dossierStatus = null;
		}

		processOrderCacheModel.dossierResume = getDossierResume();

		String dossierResume = processOrderCacheModel.dossierResume;

		if ((dossierResume != null) && (dossierResume.length() == 0)) {
			processOrderCacheModel.dossierResume = null;
		}

		Date stepDate = getStepDate();

		if (stepDate != null) {
			processOrderCacheModel.stepDate = stepDate.getTime();
		}
		else {
			processOrderCacheModel.stepDate = Long.MIN_VALUE;
		}

		processOrderCacheModel.stepNote = getStepNote();

		String stepNote = processOrderCacheModel.stepNote;

		if ((stepNote != null) && (stepNote.length() == 0)) {
			processOrderCacheModel.stepNote = null;
		}

		processOrderCacheModel.assignToUserId = getAssignToUserId();

		processOrderCacheModel.currentCondition = getCurrentCondition();

		String currentCondition = processOrderCacheModel.currentCondition;

		if ((currentCondition != null) && (currentCondition.length() == 0)) {
			processOrderCacheModel.currentCondition = null;
		}

		processOrderCacheModel.endState = getEndState();

		return processOrderCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{processOrderId=");
		sb.append(getProcessOrderId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", parentProcessOrderId=");
		sb.append(getParentProcessOrderId());
		sb.append(", dossierId=");
		sb.append(getDossierId());
		sb.append(", dossierProcessId=");
		sb.append(getDossierProcessId());
		sb.append(", dossierStepId=");
		sb.append(getDossierStepId());
		sb.append(", dossierStatus=");
		sb.append(getDossierStatus());
		sb.append(", dossierResume=");
		sb.append(getDossierResume());
		sb.append(", stepDate=");
		sb.append(getStepDate());
		sb.append(", stepNote=");
		sb.append(getStepNote());
		sb.append(", assignToUserId=");
		sb.append(getAssignToUserId());
		sb.append(", currentCondition=");
		sb.append(getCurrentCondition());
		sb.append(", endState=");
		sb.append(getEndState());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.processmgt.model.ProcessOrder");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>processOrderId</column-name><column-value><![CDATA[");
		sb.append(getProcessOrderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentProcessOrderId</column-name><column-value><![CDATA[");
		sb.append(getParentProcessOrderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierId</column-name><column-value><![CDATA[");
		sb.append(getDossierId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierProcessId</column-name><column-value><![CDATA[");
		sb.append(getDossierProcessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierStepId</column-name><column-value><![CDATA[");
		sb.append(getDossierStepId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierStatus</column-name><column-value><![CDATA[");
		sb.append(getDossierStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierResume</column-name><column-value><![CDATA[");
		sb.append(getDossierResume());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stepDate</column-name><column-value><![CDATA[");
		sb.append(getStepDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stepNote</column-name><column-value><![CDATA[");
		sb.append(getStepNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assignToUserId</column-name><column-value><![CDATA[");
		sb.append(getAssignToUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currentCondition</column-name><column-value><![CDATA[");
		sb.append(getCurrentCondition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endState</column-name><column-value><![CDATA[");
		sb.append(getEndState());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProcessOrder.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ProcessOrder.class
		};
	private long _processOrderId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _organizationId;
	private long _parentProcessOrderId;
	private long _dossierId;
	private long _dossierProcessId;
	private long _dossierStepId;
	private String _dossierStatus;
	private String _dossierResume;
	private Date _stepDate;
	private String _stepNote;
	private long _assignToUserId;
	private String _assignToUserUuid;
	private String _currentCondition;
	private int _endState;
	private ProcessOrder _escapedModel;
}