/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DocFile2ProcessOrder service. Represents a row in the &quot;oep_processmgt_docfile2processorder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.processmgt.model.impl.DocFile2ProcessOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.processmgt.model.impl.DocFile2ProcessOrderImpl}.
 * </p>
 *
 * @author trungdk
 * @see DocFile2ProcessOrder
 * @see org.oep.core.processmgt.model.impl.DocFile2ProcessOrderImpl
 * @see org.oep.core.processmgt.model.impl.DocFile2ProcessOrderModelImpl
 * @generated
 */
public interface DocFile2ProcessOrderModel extends BaseModel<DocFile2ProcessOrder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doc file2 process order model instance should use the {@link DocFile2ProcessOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this doc file2 process order.
	 *
	 * @return the primary key of this doc file2 process order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doc file2 process order.
	 *
	 * @param primaryKey the primary key of this doc file2 process order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the doc file ID of this doc file2 process order.
	 *
	 * @return the doc file ID of this doc file2 process order
	 */
	public long getDocFileId();

	/**
	 * Sets the doc file ID of this doc file2 process order.
	 *
	 * @param docFileId the doc file ID of this doc file2 process order
	 */
	public void setDocFileId(long docFileId);

	/**
	 * Returns the process order ID of this doc file2 process order.
	 *
	 * @return the process order ID of this doc file2 process order
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order ID of this doc file2 process order.
	 *
	 * @param processOrderId the process order ID of this doc file2 process order
	 */
	public void setProcessOrderId(long processOrderId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocFile2ProcessOrder docFile2ProcessOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocFile2ProcessOrder> toCacheModel();

	@Override
	public DocFile2ProcessOrder toEscapedModel();

	@Override
	public DocFile2ProcessOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}