/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierProc2Process service. Represents a row in the &quot;oep_processmgt_dossierproc2process&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.processmgt.model.impl.DossierProc2ProcessModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.processmgt.model.impl.DossierProc2ProcessImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierProc2Process
 * @see org.oep.core.processmgt.model.impl.DossierProc2ProcessImpl
 * @see org.oep.core.processmgt.model.impl.DossierProc2ProcessModelImpl
 * @generated
 */
public interface DossierProc2ProcessModel extends BaseModel<DossierProc2Process> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier proc2 process model instance should use the {@link DossierProc2Process} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier proc2 process.
	 *
	 * @return the primary key of this dossier proc2 process
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier proc2 process.
	 *
	 * @param primaryKey the primary key of this dossier proc2 process
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier proc2 process ID of this dossier proc2 process.
	 *
	 * @return the dossier proc2 process ID of this dossier proc2 process
	 */
	public long getDossierProc2ProcessId();

	/**
	 * Sets the dossier proc2 process ID of this dossier proc2 process.
	 *
	 * @param dossierProc2ProcessId the dossier proc2 process ID of this dossier proc2 process
	 */
	public void setDossierProc2ProcessId(long dossierProc2ProcessId);

	/**
	 * Returns the user ID of this dossier proc2 process.
	 *
	 * @return the user ID of this dossier proc2 process
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dossier proc2 process.
	 *
	 * @param userId the user ID of this dossier proc2 process
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dossier proc2 process.
	 *
	 * @return the user uuid of this dossier proc2 process
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dossier proc2 process.
	 *
	 * @param userUuid the user uuid of this dossier proc2 process
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this dossier proc2 process.
	 *
	 * @return the group ID of this dossier proc2 process
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dossier proc2 process.
	 *
	 * @param groupId the group ID of this dossier proc2 process
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dossier proc2 process.
	 *
	 * @return the company ID of this dossier proc2 process
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier proc2 process.
	 *
	 * @param companyId the company ID of this dossier proc2 process
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this dossier proc2 process.
	 *
	 * @return the create date of this dossier proc2 process
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier proc2 process.
	 *
	 * @param createDate the create date of this dossier proc2 process
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier proc2 process.
	 *
	 * @return the modified date of this dossier proc2 process
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier proc2 process.
	 *
	 * @param modifiedDate the modified date of this dossier proc2 process
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier proc ID of this dossier proc2 process.
	 *
	 * @return the dossier proc ID of this dossier proc2 process
	 */
	public long getDossierProcId();

	/**
	 * Sets the dossier proc ID of this dossier proc2 process.
	 *
	 * @param dossierProcId the dossier proc ID of this dossier proc2 process
	 */
	public void setDossierProcId(long dossierProcId);

	/**
	 * Returns the gov agency ID of this dossier proc2 process.
	 *
	 * @return the gov agency ID of this dossier proc2 process
	 */
	@AutoEscape
	public String getGovAgencyId();

	/**
	 * Sets the gov agency ID of this dossier proc2 process.
	 *
	 * @param govAgencyId the gov agency ID of this dossier proc2 process
	 */
	public void setGovAgencyId(String govAgencyId);

	/**
	 * Returns the gov agency name of this dossier proc2 process.
	 *
	 * @return the gov agency name of this dossier proc2 process
	 */
	@AutoEscape
	public String getGovAgencyName();

	/**
	 * Sets the gov agency name of this dossier proc2 process.
	 *
	 * @param govAgencyName the gov agency name of this dossier proc2 process
	 */
	public void setGovAgencyName(String govAgencyName);

	/**
	 * Returns the dossier process ID of this dossier proc2 process.
	 *
	 * @return the dossier process ID of this dossier proc2 process
	 */
	public long getDossierProcessId();

	/**
	 * Sets the dossier process ID of this dossier proc2 process.
	 *
	 * @param dossierProcessId the dossier process ID of this dossier proc2 process
	 */
	public void setDossierProcessId(long dossierProcessId);

	/**
	 * Returns the aaaa of this dossier proc2 process.
	 *
	 * @return the aaaa of this dossier proc2 process
	 */
	@AutoEscape
	public String getAaaa();

	/**
	 * Sets the aaaa of this dossier proc2 process.
	 *
	 * @param aaaa the aaaa of this dossier proc2 process
	 */
	public void setAaaa(String aaaa);

	/**
	 * Returns the bbb of this dossier proc2 process.
	 *
	 * @return the bbb of this dossier proc2 process
	 */
	@AutoEscape
	public String getBbb();

	/**
	 * Sets the bbb of this dossier proc2 process.
	 *
	 * @param bbb the bbb of this dossier proc2 process
	 */
	public void setBbb(String bbb);

	/**
	 * Returns the days duration of this dossier proc2 process.
	 *
	 * @return the days duration of this dossier proc2 process
	 */
	public int getDaysDuration();

	/**
	 * Sets the days duration of this dossier proc2 process.
	 *
	 * @param daysDuration the days duration of this dossier proc2 process
	 */
	public void setDaysDuration(int daysDuration);

	/**
	 * Returns the payment fee of this dossier proc2 process.
	 *
	 * @return the payment fee of this dossier proc2 process
	 */
	public int getPaymentFee();

	/**
	 * Sets the payment fee of this dossier proc2 process.
	 *
	 * @param paymentFee the payment fee of this dossier proc2 process
	 */
	public void setPaymentFee(int paymentFee);

	/**
	 * Returns the payment one gate of this dossier proc2 process.
	 *
	 * @return the payment one gate of this dossier proc2 process
	 */
	public int getPaymentOneGate();

	/**
	 * Sets the payment one gate of this dossier proc2 process.
	 *
	 * @param paymentOneGate the payment one gate of this dossier proc2 process
	 */
	public void setPaymentOneGate(int paymentOneGate);

	/**
	 * Returns the payment eservice of this dossier proc2 process.
	 *
	 * @return the payment eservice of this dossier proc2 process
	 */
	public int getPaymentEservice();

	/**
	 * Sets the payment eservice of this dossier proc2 process.
	 *
	 * @param paymentEservice the payment eservice of this dossier proc2 process
	 */
	public void setPaymentEservice(int paymentEservice);

	/**
	 * Returns the organization ID of this dossier proc2 process.
	 *
	 * @return the organization ID of this dossier proc2 process
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this dossier proc2 process.
	 *
	 * @param organizationId the organization ID of this dossier proc2 process
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the eb partnership ID of this dossier proc2 process.
	 *
	 * @return the eb partnership ID of this dossier proc2 process
	 */
	public long getEbPartnershipId();

	/**
	 * Sets the eb partnership ID of this dossier proc2 process.
	 *
	 * @param ebPartnershipId the eb partnership ID of this dossier proc2 process
	 */
	public void setEbPartnershipId(long ebPartnershipId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DossierProc2Process dossierProc2Process);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DossierProc2Process> toCacheModel();

	@Override
	public DossierProc2Process toEscapedModel();

	@Override
	public DossierProc2Process toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}