/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.processmgt.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserAssignment service. Represents a row in the &quot;oep_processmgt_userassignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.oep.core.processmgt.model.impl.UserAssignmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.oep.core.processmgt.model.impl.UserAssignmentImpl}.
 * </p>
 *
 * @author trungdk
 * @see UserAssignment
 * @see org.oep.core.processmgt.model.impl.UserAssignmentImpl
 * @see org.oep.core.processmgt.model.impl.UserAssignmentModelImpl
 * @generated
 */
public interface UserAssignmentModel extends BaseModel<UserAssignment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user assignment model instance should use the {@link UserAssignment} interface instead.
	 */

	/**
	 * Returns the primary key of this user assignment.
	 *
	 * @return the primary key of this user assignment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user assignment.
	 *
	 * @param primaryKey the primary key of this user assignment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user assignment ID of this user assignment.
	 *
	 * @return the user assignment ID of this user assignment
	 */
	public long getUserAssignmentId();

	/**
	 * Sets the user assignment ID of this user assignment.
	 *
	 * @param userAssignmentId the user assignment ID of this user assignment
	 */
	public void setUserAssignmentId(long userAssignmentId);

	/**
	 * Returns the user ID of this user assignment.
	 *
	 * @return the user ID of this user assignment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user assignment.
	 *
	 * @param userId the user ID of this user assignment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user assignment.
	 *
	 * @return the user uuid of this user assignment
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user assignment.
	 *
	 * @param userUuid the user uuid of this user assignment
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this user assignment.
	 *
	 * @return the group ID of this user assignment
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user assignment.
	 *
	 * @param groupId the group ID of this user assignment
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user assignment.
	 *
	 * @return the company ID of this user assignment
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this user assignment.
	 *
	 * @param companyId the company ID of this user assignment
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this user assignment.
	 *
	 * @return the create date of this user assignment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user assignment.
	 *
	 * @param createDate the create date of this user assignment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the process order ID of this user assignment.
	 *
	 * @return the process order ID of this user assignment
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order ID of this user assignment.
	 *
	 * @param processOrderId the process order ID of this user assignment
	 */
	public void setProcessOrderId(long processOrderId);

	/**
	 * Returns the dossier step ID of this user assignment.
	 *
	 * @return the dossier step ID of this user assignment
	 */
	public long getDossierStepId();

	/**
	 * Sets the dossier step ID of this user assignment.
	 *
	 * @param dossierStepId the dossier step ID of this user assignment
	 */
	public void setDossierStepId(long dossierStepId);

	/**
	 * Returns the assign to user ID of this user assignment.
	 *
	 * @return the assign to user ID of this user assignment
	 */
	public long getAssignToUserId();

	/**
	 * Sets the assign to user ID of this user assignment.
	 *
	 * @param assignToUserId the assign to user ID of this user assignment
	 */
	public void setAssignToUserId(long assignToUserId);

	/**
	 * Returns the assign to user uuid of this user assignment.
	 *
	 * @return the assign to user uuid of this user assignment
	 * @throws SystemException if a system exception occurred
	 */
	public String getAssignToUserUuid() throws SystemException;

	/**
	 * Sets the assign to user uuid of this user assignment.
	 *
	 * @param assignToUserUuid the assign to user uuid of this user assignment
	 */
	public void setAssignToUserUuid(String assignToUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserAssignment userAssignment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserAssignment> toCacheModel();

	@Override
	public UserAssignment toEscapedModel();

	@Override
	public UserAssignment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}