/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.dossiermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.core.dossiermgt.model.DossierDoc;
import org.oep.core.dossiermgt.model.DossierDocModel;
import org.oep.core.dossiermgt.model.DossierDocSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DossierDoc service. Represents a row in the &quot;oep_dossiermgt_dossierdoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.core.dossiermgt.model.DossierDocModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DossierDocImpl}.
 * </p>
 *
 * @author trungdk
 * @see DossierDocImpl
 * @see org.oep.core.dossiermgt.model.DossierDoc
 * @see org.oep.core.dossiermgt.model.DossierDocModel
 * @generated
 */
@JSON(strict = true)
public class DossierDocModelImpl extends BaseModelImpl<DossierDoc>
	implements DossierDocModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dossier doc model instance should use the {@link org.oep.core.dossiermgt.model.DossierDoc} interface instead.
	 */
	public static final String TABLE_NAME = "oep_dossiermgt_dossierdoc";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dossierDocId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "dossierProcId", Types.BIGINT },
			{ "dossierDocNo", Types.VARCHAR },
			{ "dossierDocName", Types.VARCHAR },
			{ "note", Types.VARCHAR },
			{ "sequenceNo", Types.INTEGER },
			{ "defaultDocTemplateId", Types.BIGINT },
			{ "validationType", Types.INTEGER },
			{ "numberOfFile", Types.INTEGER },
			{ "onlineForm", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_dossiermgt_dossierdoc (dossierDocId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,dossierProcId LONG,dossierDocNo VARCHAR(30) null,dossierDocName VARCHAR(100) null,note VARCHAR(255) null,sequenceNo INTEGER,defaultDocTemplateId LONG,validationType INTEGER,numberOfFile INTEGER,onlineForm VARCHAR(30) null)";
	public static final String TABLE_SQL_DROP = "drop table oep_dossiermgt_dossierdoc";
	public static final String ORDER_BY_JPQL = " ORDER BY dossierDoc.dossierDocId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_dossiermgt_dossierdoc.dossierDocId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.core.dossiermgt.model.DossierDoc"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.core.dossiermgt.model.DossierDoc"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DossierDoc toModel(DossierDocSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DossierDoc model = new DossierDocImpl();

		model.setDossierDocId(soapModel.getDossierDocId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDossierProcId(soapModel.getDossierProcId());
		model.setDossierDocNo(soapModel.getDossierDocNo());
		model.setDossierDocName(soapModel.getDossierDocName());
		model.setNote(soapModel.getNote());
		model.setSequenceNo(soapModel.getSequenceNo());
		model.setDefaultDocTemplateId(soapModel.getDefaultDocTemplateId());
		model.setValidationType(soapModel.getValidationType());
		model.setNumberOfFile(soapModel.getNumberOfFile());
		model.setOnlineForm(soapModel.getOnlineForm());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DossierDoc> toModels(DossierDocSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DossierDoc> models = new ArrayList<DossierDoc>(soapModels.length);

		for (DossierDocSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.core.dossiermgt.model.DossierDoc"));

	public DossierDocModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dossierDocId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDossierDocId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dossierDocId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DossierDoc.class;
	}

	@Override
	public String getModelClassName() {
		return DossierDoc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dossierDocId", getDossierDocId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("dossierProcId", getDossierProcId());
		attributes.put("dossierDocNo", getDossierDocNo());
		attributes.put("dossierDocName", getDossierDocName());
		attributes.put("note", getNote());
		attributes.put("sequenceNo", getSequenceNo());
		attributes.put("defaultDocTemplateId", getDefaultDocTemplateId());
		attributes.put("validationType", getValidationType());
		attributes.put("numberOfFile", getNumberOfFile());
		attributes.put("onlineForm", getOnlineForm());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dossierDocId = (Long)attributes.get("dossierDocId");

		if (dossierDocId != null) {
			setDossierDocId(dossierDocId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long dossierProcId = (Long)attributes.get("dossierProcId");

		if (dossierProcId != null) {
			setDossierProcId(dossierProcId);
		}

		String dossierDocNo = (String)attributes.get("dossierDocNo");

		if (dossierDocNo != null) {
			setDossierDocNo(dossierDocNo);
		}

		String dossierDocName = (String)attributes.get("dossierDocName");

		if (dossierDocName != null) {
			setDossierDocName(dossierDocName);
		}

		String note = (String)attributes.get("note");

		if (note != null) {
			setNote(note);
		}

		Integer sequenceNo = (Integer)attributes.get("sequenceNo");

		if (sequenceNo != null) {
			setSequenceNo(sequenceNo);
		}

		Long defaultDocTemplateId = (Long)attributes.get("defaultDocTemplateId");

		if (defaultDocTemplateId != null) {
			setDefaultDocTemplateId(defaultDocTemplateId);
		}

		Integer validationType = (Integer)attributes.get("validationType");

		if (validationType != null) {
			setValidationType(validationType);
		}

		Integer numberOfFile = (Integer)attributes.get("numberOfFile");

		if (numberOfFile != null) {
			setNumberOfFile(numberOfFile);
		}

		String onlineForm = (String)attributes.get("onlineForm");

		if (onlineForm != null) {
			setOnlineForm(onlineForm);
		}
	}

	@JSON
	@Override
	public long getDossierDocId() {
		return _dossierDocId;
	}

	@Override
	public void setDossierDocId(long dossierDocId) {
		_dossierDocId = dossierDocId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDossierProcId() {
		return _dossierProcId;
	}

	@Override
	public void setDossierProcId(long dossierProcId) {
		_dossierProcId = dossierProcId;
	}

	@JSON
	@Override
	public String getDossierDocNo() {
		if (_dossierDocNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierDocNo;
		}
	}

	@Override
	public void setDossierDocNo(String dossierDocNo) {
		_dossierDocNo = dossierDocNo;
	}

	@JSON
	@Override
	public String getDossierDocName() {
		if (_dossierDocName == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierDocName;
		}
	}

	@Override
	public void setDossierDocName(String dossierDocName) {
		_dossierDocName = dossierDocName;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		_note = note;
	}

	@JSON
	@Override
	public int getSequenceNo() {
		return _sequenceNo;
	}

	@Override
	public void setSequenceNo(int sequenceNo) {
		_sequenceNo = sequenceNo;
	}

	@JSON
	@Override
	public long getDefaultDocTemplateId() {
		return _defaultDocTemplateId;
	}

	@Override
	public void setDefaultDocTemplateId(long defaultDocTemplateId) {
		_defaultDocTemplateId = defaultDocTemplateId;
	}

	@JSON
	@Override
	public int getValidationType() {
		return _validationType;
	}

	@Override
	public void setValidationType(int validationType) {
		_validationType = validationType;
	}

	@JSON
	@Override
	public int getNumberOfFile() {
		return _numberOfFile;
	}

	@Override
	public void setNumberOfFile(int numberOfFile) {
		_numberOfFile = numberOfFile;
	}

	@JSON
	@Override
	public String getOnlineForm() {
		if (_onlineForm == null) {
			return StringPool.BLANK;
		}
		else {
			return _onlineForm;
		}
	}

	@Override
	public void setOnlineForm(String onlineForm) {
		_onlineForm = onlineForm;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DossierDoc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DossierDoc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DossierDoc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DossierDocImpl dossierDocImpl = new DossierDocImpl();

		dossierDocImpl.setDossierDocId(getDossierDocId());
		dossierDocImpl.setUserId(getUserId());
		dossierDocImpl.setGroupId(getGroupId());
		dossierDocImpl.setCompanyId(getCompanyId());
		dossierDocImpl.setCreateDate(getCreateDate());
		dossierDocImpl.setModifiedDate(getModifiedDate());
		dossierDocImpl.setDossierProcId(getDossierProcId());
		dossierDocImpl.setDossierDocNo(getDossierDocNo());
		dossierDocImpl.setDossierDocName(getDossierDocName());
		dossierDocImpl.setNote(getNote());
		dossierDocImpl.setSequenceNo(getSequenceNo());
		dossierDocImpl.setDefaultDocTemplateId(getDefaultDocTemplateId());
		dossierDocImpl.setValidationType(getValidationType());
		dossierDocImpl.setNumberOfFile(getNumberOfFile());
		dossierDocImpl.setOnlineForm(getOnlineForm());

		dossierDocImpl.resetOriginalValues();

		return dossierDocImpl;
	}

	@Override
	public int compareTo(DossierDoc dossierDoc) {
		long primaryKey = dossierDoc.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DossierDoc)) {
			return false;
		}

		DossierDoc dossierDoc = (DossierDoc)obj;

		long primaryKey = dossierDoc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DossierDoc> toCacheModel() {
		DossierDocCacheModel dossierDocCacheModel = new DossierDocCacheModel();

		dossierDocCacheModel.dossierDocId = getDossierDocId();

		dossierDocCacheModel.userId = getUserId();

		dossierDocCacheModel.groupId = getGroupId();

		dossierDocCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			dossierDocCacheModel.createDate = createDate.getTime();
		}
		else {
			dossierDocCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dossierDocCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dossierDocCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dossierDocCacheModel.dossierProcId = getDossierProcId();

		dossierDocCacheModel.dossierDocNo = getDossierDocNo();

		String dossierDocNo = dossierDocCacheModel.dossierDocNo;

		if ((dossierDocNo != null) && (dossierDocNo.length() == 0)) {
			dossierDocCacheModel.dossierDocNo = null;
		}

		dossierDocCacheModel.dossierDocName = getDossierDocName();

		String dossierDocName = dossierDocCacheModel.dossierDocName;

		if ((dossierDocName != null) && (dossierDocName.length() == 0)) {
			dossierDocCacheModel.dossierDocName = null;
		}

		dossierDocCacheModel.note = getNote();

		String note = dossierDocCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			dossierDocCacheModel.note = null;
		}

		dossierDocCacheModel.sequenceNo = getSequenceNo();

		dossierDocCacheModel.defaultDocTemplateId = getDefaultDocTemplateId();

		dossierDocCacheModel.validationType = getValidationType();

		dossierDocCacheModel.numberOfFile = getNumberOfFile();

		dossierDocCacheModel.onlineForm = getOnlineForm();

		String onlineForm = dossierDocCacheModel.onlineForm;

		if ((onlineForm != null) && (onlineForm.length() == 0)) {
			dossierDocCacheModel.onlineForm = null;
		}

		return dossierDocCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{dossierDocId=");
		sb.append(getDossierDocId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", dossierProcId=");
		sb.append(getDossierProcId());
		sb.append(", dossierDocNo=");
		sb.append(getDossierDocNo());
		sb.append(", dossierDocName=");
		sb.append(getDossierDocName());
		sb.append(", note=");
		sb.append(getNote());
		sb.append(", sequenceNo=");
		sb.append(getSequenceNo());
		sb.append(", defaultDocTemplateId=");
		sb.append(getDefaultDocTemplateId());
		sb.append(", validationType=");
		sb.append(getValidationType());
		sb.append(", numberOfFile=");
		sb.append(getNumberOfFile());
		sb.append(", onlineForm=");
		sb.append(getOnlineForm());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("org.oep.core.dossiermgt.model.DossierDoc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dossierDocId</column-name><column-value><![CDATA[");
		sb.append(getDossierDocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierProcId</column-name><column-value><![CDATA[");
		sb.append(getDossierProcId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierDocNo</column-name><column-value><![CDATA[");
		sb.append(getDossierDocNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierDocName</column-name><column-value><![CDATA[");
		sb.append(getDossierDocName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sequenceNo</column-name><column-value><![CDATA[");
		sb.append(getSequenceNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>defaultDocTemplateId</column-name><column-value><![CDATA[");
		sb.append(getDefaultDocTemplateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>validationType</column-name><column-value><![CDATA[");
		sb.append(getValidationType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfFile</column-name><column-value><![CDATA[");
		sb.append(getNumberOfFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>onlineForm</column-name><column-value><![CDATA[");
		sb.append(getOnlineForm());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DossierDoc.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DossierDoc.class
		};
	private long _dossierDocId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _dossierProcId;
	private String _dossierDocNo;
	private String _dossierDocName;
	private String _note;
	private int _sequenceNo;
	private long _defaultDocTemplateId;
	private int _validationType;
	private int _numberOfFile;
	private String _onlineForm;
	private DossierDoc _escapedModel;
}