/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.usermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.oep.usermgt.model.Business;
import org.oep.usermgt.model.BusinessModel;
import org.oep.usermgt.model.BusinessSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Business service. Represents a row in the &quot;oep_usermgt_business&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.oep.usermgt.model.BusinessModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessImpl}.
 * </p>
 *
 * @author NQMINH
 * @see BusinessImpl
 * @see org.oep.usermgt.model.Business
 * @see org.oep.usermgt.model.BusinessModel
 * @generated
 */
@JSON(strict = true)
public class BusinessModelImpl extends BaseModelImpl<Business>
	implements BusinessModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a business model instance should use the {@link org.oep.usermgt.model.Business} interface instead.
	 */
	public static final String TABLE_NAME = "oep_usermgt_business";
	public static final Object[][] TABLE_COLUMNS = {
			{ "businessId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "organizationId", Types.BIGINT },
			{ "masterUserId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "enName", Types.VARCHAR },
			{ "shortName", Types.VARCHAR },
			{ "address", Types.VARCHAR },
			{ "cityNo", Types.VARCHAR },
			{ "cityName", Types.VARCHAR },
			{ "districtNo", Types.VARCHAR },
			{ "districtName", Types.VARCHAR },
			{ "wardNo", Types.VARCHAR },
			{ "wardName", Types.VARCHAR },
			{ "gpsPosition", Types.VARCHAR },
			{ "telNo", Types.VARCHAR },
			{ "fax", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "businessNo", Types.VARCHAR },
			{ "businessType", Types.VARCHAR },
			{ "registerAgent", Types.VARCHAR },
			{ "registerDate", Types.TIMESTAMP },
			{ "representative", Types.VARCHAR },
			{ "representativeRole", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table oep_usermgt_business (businessId LONG not null primary key,userId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,organizationId LONG,masterUserId LONG,name VARCHAR(75) null,enName VARCHAR(75) null,shortName VARCHAR(75) null,address VARCHAR(75) null,cityNo VARCHAR(75) null,cityName VARCHAR(75) null,districtNo VARCHAR(75) null,districtName VARCHAR(75) null,wardNo VARCHAR(75) null,wardName VARCHAR(75) null,gpsPosition VARCHAR(75) null,telNo VARCHAR(75) null,fax VARCHAR(75) null,email VARCHAR(75) null,businessNo VARCHAR(75) null,businessType VARCHAR(75) null,registerAgent VARCHAR(75) null,registerDate DATE null,representative VARCHAR(75) null,representativeRole VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table oep_usermgt_business";
	public static final String ORDER_BY_JPQL = " ORDER BY business.businessId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oep_usermgt_business.businessId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.oep.usermgt.model.Business"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.oep.usermgt.model.Business"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.oep.usermgt.model.Business"),
			true);
	public static long CITYNO_COLUMN_BITMASK = 1L;
	public static long DISTRICTNO_COLUMN_BITMASK = 2L;
	public static long MASTERUSERID_COLUMN_BITMASK = 4L;
	public static long ORGANIZATIONID_COLUMN_BITMASK = 8L;
	public static long REGISTERAGENT_COLUMN_BITMASK = 16L;
	public static long WARDNO_COLUMN_BITMASK = 32L;
	public static long BUSINESSID_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Business toModel(BusinessSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Business model = new BusinessImpl();

		model.setBusinessId(soapModel.getBusinessId());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setMasterUserId(soapModel.getMasterUserId());
		model.setName(soapModel.getName());
		model.setEnName(soapModel.getEnName());
		model.setShortName(soapModel.getShortName());
		model.setAddress(soapModel.getAddress());
		model.setCityNo(soapModel.getCityNo());
		model.setCityName(soapModel.getCityName());
		model.setDistrictNo(soapModel.getDistrictNo());
		model.setDistrictName(soapModel.getDistrictName());
		model.setWardNo(soapModel.getWardNo());
		model.setWardName(soapModel.getWardName());
		model.setGpsPosition(soapModel.getGpsPosition());
		model.setTelNo(soapModel.getTelNo());
		model.setFax(soapModel.getFax());
		model.setEmail(soapModel.getEmail());
		model.setBusinessNo(soapModel.getBusinessNo());
		model.setBusinessType(soapModel.getBusinessType());
		model.setRegisterAgent(soapModel.getRegisterAgent());
		model.setRegisterDate(soapModel.getRegisterDate());
		model.setRepresentative(soapModel.getRepresentative());
		model.setRepresentativeRole(soapModel.getRepresentativeRole());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Business> toModels(BusinessSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Business> models = new ArrayList<Business>(soapModels.length);

		for (BusinessSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.oep.usermgt.model.Business"));

	public BusinessModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _businessId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBusinessId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _businessId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Business.class;
	}

	@Override
	public String getModelClassName() {
		return Business.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("businessId", getBusinessId());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("masterUserId", getMasterUserId());
		attributes.put("name", getName());
		attributes.put("enName", getEnName());
		attributes.put("shortName", getShortName());
		attributes.put("address", getAddress());
		attributes.put("cityNo", getCityNo());
		attributes.put("cityName", getCityName());
		attributes.put("districtNo", getDistrictNo());
		attributes.put("districtName", getDistrictName());
		attributes.put("wardNo", getWardNo());
		attributes.put("wardName", getWardName());
		attributes.put("gpsPosition", getGpsPosition());
		attributes.put("telNo", getTelNo());
		attributes.put("fax", getFax());
		attributes.put("email", getEmail());
		attributes.put("businessNo", getBusinessNo());
		attributes.put("businessType", getBusinessType());
		attributes.put("registerAgent", getRegisterAgent());
		attributes.put("registerDate", getRegisterDate());
		attributes.put("representative", getRepresentative());
		attributes.put("representativeRole", getRepresentativeRole());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long businessId = (Long)attributes.get("businessId");

		if (businessId != null) {
			setBusinessId(businessId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		Long masterUserId = (Long)attributes.get("masterUserId");

		if (masterUserId != null) {
			setMasterUserId(masterUserId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String enName = (String)attributes.get("enName");

		if (enName != null) {
			setEnName(enName);
		}

		String shortName = (String)attributes.get("shortName");

		if (shortName != null) {
			setShortName(shortName);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String cityNo = (String)attributes.get("cityNo");

		if (cityNo != null) {
			setCityNo(cityNo);
		}

		String cityName = (String)attributes.get("cityName");

		if (cityName != null) {
			setCityName(cityName);
		}

		String districtNo = (String)attributes.get("districtNo");

		if (districtNo != null) {
			setDistrictNo(districtNo);
		}

		String districtName = (String)attributes.get("districtName");

		if (districtName != null) {
			setDistrictName(districtName);
		}

		String wardNo = (String)attributes.get("wardNo");

		if (wardNo != null) {
			setWardNo(wardNo);
		}

		String wardName = (String)attributes.get("wardName");

		if (wardName != null) {
			setWardName(wardName);
		}

		String gpsPosition = (String)attributes.get("gpsPosition");

		if (gpsPosition != null) {
			setGpsPosition(gpsPosition);
		}

		String telNo = (String)attributes.get("telNo");

		if (telNo != null) {
			setTelNo(telNo);
		}

		String fax = (String)attributes.get("fax");

		if (fax != null) {
			setFax(fax);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String businessNo = (String)attributes.get("businessNo");

		if (businessNo != null) {
			setBusinessNo(businessNo);
		}

		String businessType = (String)attributes.get("businessType");

		if (businessType != null) {
			setBusinessType(businessType);
		}

		String registerAgent = (String)attributes.get("registerAgent");

		if (registerAgent != null) {
			setRegisterAgent(registerAgent);
		}

		Date registerDate = (Date)attributes.get("registerDate");

		if (registerDate != null) {
			setRegisterDate(registerDate);
		}

		String representative = (String)attributes.get("representative");

		if (representative != null) {
			setRepresentative(representative);
		}

		String representativeRole = (String)attributes.get("representativeRole");

		if (representativeRole != null) {
			setRepresentativeRole(representativeRole);
		}
	}

	@JSON
	@Override
	public long getBusinessId() {
		return _businessId;
	}

	@Override
	public void setBusinessId(long businessId) {
		_businessId = businessId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@JSON
	@Override
	public long getMasterUserId() {
		return _masterUserId;
	}

	@Override
	public void setMasterUserId(long masterUserId) {
		_columnBitmask |= MASTERUSERID_COLUMN_BITMASK;

		if (!_setOriginalMasterUserId) {
			_setOriginalMasterUserId = true;

			_originalMasterUserId = _masterUserId;
		}

		_masterUserId = masterUserId;
	}

	@Override
	public String getMasterUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getMasterUserId(), "uuid",
			_masterUserUuid);
	}

	@Override
	public void setMasterUserUuid(String masterUserUuid) {
		_masterUserUuid = masterUserUuid;
	}

	public long getOriginalMasterUserId() {
		return _originalMasterUserId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getEnName() {
		if (_enName == null) {
			return StringPool.BLANK;
		}
		else {
			return _enName;
		}
	}

	@Override
	public void setEnName(String enName) {
		_enName = enName;
	}

	@JSON
	@Override
	public String getShortName() {
		if (_shortName == null) {
			return StringPool.BLANK;
		}
		else {
			return _shortName;
		}
	}

	@Override
	public void setShortName(String shortName) {
		_shortName = shortName;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getCityNo() {
		if (_cityNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityNo;
		}
	}

	@Override
	public void setCityNo(String cityNo) {
		_columnBitmask |= CITYNO_COLUMN_BITMASK;

		if (_originalCityNo == null) {
			_originalCityNo = _cityNo;
		}

		_cityNo = cityNo;
	}

	public String getOriginalCityNo() {
		return GetterUtil.getString(_originalCityNo);
	}

	@JSON
	@Override
	public String getCityName() {
		if (_cityName == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityName;
		}
	}

	@Override
	public void setCityName(String cityName) {
		_cityName = cityName;
	}

	@JSON
	@Override
	public String getDistrictNo() {
		if (_districtNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtNo;
		}
	}

	@Override
	public void setDistrictNo(String districtNo) {
		_columnBitmask |= DISTRICTNO_COLUMN_BITMASK;

		if (_originalDistrictNo == null) {
			_originalDistrictNo = _districtNo;
		}

		_districtNo = districtNo;
	}

	public String getOriginalDistrictNo() {
		return GetterUtil.getString(_originalDistrictNo);
	}

	@JSON
	@Override
	public String getDistrictName() {
		if (_districtName == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtName;
		}
	}

	@Override
	public void setDistrictName(String districtName) {
		_districtName = districtName;
	}

	@JSON
	@Override
	public String getWardNo() {
		if (_wardNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardNo;
		}
	}

	@Override
	public void setWardNo(String wardNo) {
		_columnBitmask |= WARDNO_COLUMN_BITMASK;

		if (_originalWardNo == null) {
			_originalWardNo = _wardNo;
		}

		_wardNo = wardNo;
	}

	public String getOriginalWardNo() {
		return GetterUtil.getString(_originalWardNo);
	}

	@JSON
	@Override
	public String getWardName() {
		if (_wardName == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardName;
		}
	}

	@Override
	public void setWardName(String wardName) {
		_wardName = wardName;
	}

	@JSON
	@Override
	public String getGpsPosition() {
		if (_gpsPosition == null) {
			return StringPool.BLANK;
		}
		else {
			return _gpsPosition;
		}
	}

	@Override
	public void setGpsPosition(String gpsPosition) {
		_gpsPosition = gpsPosition;
	}

	@JSON
	@Override
	public String getTelNo() {
		if (_telNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _telNo;
		}
	}

	@Override
	public void setTelNo(String telNo) {
		_telNo = telNo;
	}

	@JSON
	@Override
	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	@Override
	public void setFax(String fax) {
		_fax = fax;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getBusinessNo() {
		if (_businessNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _businessNo;
		}
	}

	@Override
	public void setBusinessNo(String businessNo) {
		_businessNo = businessNo;
	}

	@JSON
	@Override
	public String getBusinessType() {
		if (_businessType == null) {
			return StringPool.BLANK;
		}
		else {
			return _businessType;
		}
	}

	@Override
	public void setBusinessType(String businessType) {
		_businessType = businessType;
	}

	@JSON
	@Override
	public String getRegisterAgent() {
		if (_registerAgent == null) {
			return StringPool.BLANK;
		}
		else {
			return _registerAgent;
		}
	}

	@Override
	public void setRegisterAgent(String registerAgent) {
		_columnBitmask |= REGISTERAGENT_COLUMN_BITMASK;

		if (_originalRegisterAgent == null) {
			_originalRegisterAgent = _registerAgent;
		}

		_registerAgent = registerAgent;
	}

	public String getOriginalRegisterAgent() {
		return GetterUtil.getString(_originalRegisterAgent);
	}

	@JSON
	@Override
	public Date getRegisterDate() {
		return _registerDate;
	}

	@Override
	public void setRegisterDate(Date registerDate) {
		_registerDate = registerDate;
	}

	@JSON
	@Override
	public String getRepresentative() {
		if (_representative == null) {
			return StringPool.BLANK;
		}
		else {
			return _representative;
		}
	}

	@Override
	public void setRepresentative(String representative) {
		_representative = representative;
	}

	@JSON
	@Override
	public String getRepresentativeRole() {
		if (_representativeRole == null) {
			return StringPool.BLANK;
		}
		else {
			return _representativeRole;
		}
	}

	@Override
	public void setRepresentativeRole(String representativeRole) {
		_representativeRole = representativeRole;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Business.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Business toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Business)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BusinessImpl businessImpl = new BusinessImpl();

		businessImpl.setBusinessId(getBusinessId());
		businessImpl.setUserId(getUserId());
		businessImpl.setGroupId(getGroupId());
		businessImpl.setCompanyId(getCompanyId());
		businessImpl.setCreateDate(getCreateDate());
		businessImpl.setModifiedDate(getModifiedDate());
		businessImpl.setOrganizationId(getOrganizationId());
		businessImpl.setMasterUserId(getMasterUserId());
		businessImpl.setName(getName());
		businessImpl.setEnName(getEnName());
		businessImpl.setShortName(getShortName());
		businessImpl.setAddress(getAddress());
		businessImpl.setCityNo(getCityNo());
		businessImpl.setCityName(getCityName());
		businessImpl.setDistrictNo(getDistrictNo());
		businessImpl.setDistrictName(getDistrictName());
		businessImpl.setWardNo(getWardNo());
		businessImpl.setWardName(getWardName());
		businessImpl.setGpsPosition(getGpsPosition());
		businessImpl.setTelNo(getTelNo());
		businessImpl.setFax(getFax());
		businessImpl.setEmail(getEmail());
		businessImpl.setBusinessNo(getBusinessNo());
		businessImpl.setBusinessType(getBusinessType());
		businessImpl.setRegisterAgent(getRegisterAgent());
		businessImpl.setRegisterDate(getRegisterDate());
		businessImpl.setRepresentative(getRepresentative());
		businessImpl.setRepresentativeRole(getRepresentativeRole());

		businessImpl.resetOriginalValues();

		return businessImpl;
	}

	@Override
	public int compareTo(Business business) {
		long primaryKey = business.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Business)) {
			return false;
		}

		Business business = (Business)obj;

		long primaryKey = business.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BusinessModelImpl businessModelImpl = this;

		businessModelImpl._originalOrganizationId = businessModelImpl._organizationId;

		businessModelImpl._setOriginalOrganizationId = false;

		businessModelImpl._originalMasterUserId = businessModelImpl._masterUserId;

		businessModelImpl._setOriginalMasterUserId = false;

		businessModelImpl._originalCityNo = businessModelImpl._cityNo;

		businessModelImpl._originalDistrictNo = businessModelImpl._districtNo;

		businessModelImpl._originalWardNo = businessModelImpl._wardNo;

		businessModelImpl._originalRegisterAgent = businessModelImpl._registerAgent;

		businessModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Business> toCacheModel() {
		BusinessCacheModel businessCacheModel = new BusinessCacheModel();

		businessCacheModel.businessId = getBusinessId();

		businessCacheModel.userId = getUserId();

		businessCacheModel.groupId = getGroupId();

		businessCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			businessCacheModel.createDate = createDate.getTime();
		}
		else {
			businessCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			businessCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			businessCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		businessCacheModel.organizationId = getOrganizationId();

		businessCacheModel.masterUserId = getMasterUserId();

		businessCacheModel.name = getName();

		String name = businessCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			businessCacheModel.name = null;
		}

		businessCacheModel.enName = getEnName();

		String enName = businessCacheModel.enName;

		if ((enName != null) && (enName.length() == 0)) {
			businessCacheModel.enName = null;
		}

		businessCacheModel.shortName = getShortName();

		String shortName = businessCacheModel.shortName;

		if ((shortName != null) && (shortName.length() == 0)) {
			businessCacheModel.shortName = null;
		}

		businessCacheModel.address = getAddress();

		String address = businessCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			businessCacheModel.address = null;
		}

		businessCacheModel.cityNo = getCityNo();

		String cityNo = businessCacheModel.cityNo;

		if ((cityNo != null) && (cityNo.length() == 0)) {
			businessCacheModel.cityNo = null;
		}

		businessCacheModel.cityName = getCityName();

		String cityName = businessCacheModel.cityName;

		if ((cityName != null) && (cityName.length() == 0)) {
			businessCacheModel.cityName = null;
		}

		businessCacheModel.districtNo = getDistrictNo();

		String districtNo = businessCacheModel.districtNo;

		if ((districtNo != null) && (districtNo.length() == 0)) {
			businessCacheModel.districtNo = null;
		}

		businessCacheModel.districtName = getDistrictName();

		String districtName = businessCacheModel.districtName;

		if ((districtName != null) && (districtName.length() == 0)) {
			businessCacheModel.districtName = null;
		}

		businessCacheModel.wardNo = getWardNo();

		String wardNo = businessCacheModel.wardNo;

		if ((wardNo != null) && (wardNo.length() == 0)) {
			businessCacheModel.wardNo = null;
		}

		businessCacheModel.wardName = getWardName();

		String wardName = businessCacheModel.wardName;

		if ((wardName != null) && (wardName.length() == 0)) {
			businessCacheModel.wardName = null;
		}

		businessCacheModel.gpsPosition = getGpsPosition();

		String gpsPosition = businessCacheModel.gpsPosition;

		if ((gpsPosition != null) && (gpsPosition.length() == 0)) {
			businessCacheModel.gpsPosition = null;
		}

		businessCacheModel.telNo = getTelNo();

		String telNo = businessCacheModel.telNo;

		if ((telNo != null) && (telNo.length() == 0)) {
			businessCacheModel.telNo = null;
		}

		businessCacheModel.fax = getFax();

		String fax = businessCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			businessCacheModel.fax = null;
		}

		businessCacheModel.email = getEmail();

		String email = businessCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			businessCacheModel.email = null;
		}

		businessCacheModel.businessNo = getBusinessNo();

		String businessNo = businessCacheModel.businessNo;

		if ((businessNo != null) && (businessNo.length() == 0)) {
			businessCacheModel.businessNo = null;
		}

		businessCacheModel.businessType = getBusinessType();

		String businessType = businessCacheModel.businessType;

		if ((businessType != null) && (businessType.length() == 0)) {
			businessCacheModel.businessType = null;
		}

		businessCacheModel.registerAgent = getRegisterAgent();

		String registerAgent = businessCacheModel.registerAgent;

		if ((registerAgent != null) && (registerAgent.length() == 0)) {
			businessCacheModel.registerAgent = null;
		}

		Date registerDate = getRegisterDate();

		if (registerDate != null) {
			businessCacheModel.registerDate = registerDate.getTime();
		}
		else {
			businessCacheModel.registerDate = Long.MIN_VALUE;
		}

		businessCacheModel.representative = getRepresentative();

		String representative = businessCacheModel.representative;

		if ((representative != null) && (representative.length() == 0)) {
			businessCacheModel.representative = null;
		}

		businessCacheModel.representativeRole = getRepresentativeRole();

		String representativeRole = businessCacheModel.representativeRole;

		if ((representativeRole != null) && (representativeRole.length() == 0)) {
			businessCacheModel.representativeRole = null;
		}

		return businessCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(57);

		sb.append("{businessId=");
		sb.append(getBusinessId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", masterUserId=");
		sb.append(getMasterUserId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", enName=");
		sb.append(getEnName());
		sb.append(", shortName=");
		sb.append(getShortName());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", cityNo=");
		sb.append(getCityNo());
		sb.append(", cityName=");
		sb.append(getCityName());
		sb.append(", districtNo=");
		sb.append(getDistrictNo());
		sb.append(", districtName=");
		sb.append(getDistrictName());
		sb.append(", wardNo=");
		sb.append(getWardNo());
		sb.append(", wardName=");
		sb.append(getWardName());
		sb.append(", gpsPosition=");
		sb.append(getGpsPosition());
		sb.append(", telNo=");
		sb.append(getTelNo());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", businessNo=");
		sb.append(getBusinessNo());
		sb.append(", businessType=");
		sb.append(getBusinessType());
		sb.append(", registerAgent=");
		sb.append(getRegisterAgent());
		sb.append(", registerDate=");
		sb.append(getRegisterDate());
		sb.append(", representative=");
		sb.append(getRepresentative());
		sb.append(", representativeRole=");
		sb.append(getRepresentativeRole());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(88);

		sb.append("<model><model-name>");
		sb.append("org.oep.usermgt.model.Business");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>businessId</column-name><column-value><![CDATA[");
		sb.append(getBusinessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterUserId</column-name><column-value><![CDATA[");
		sb.append(getMasterUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enName</column-name><column-value><![CDATA[");
		sb.append(getEnName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shortName</column-name><column-value><![CDATA[");
		sb.append(getShortName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityNo</column-name><column-value><![CDATA[");
		sb.append(getCityNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityName</column-name><column-value><![CDATA[");
		sb.append(getCityName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtNo</column-name><column-value><![CDATA[");
		sb.append(getDistrictNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtName</column-name><column-value><![CDATA[");
		sb.append(getDistrictName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardNo</column-name><column-value><![CDATA[");
		sb.append(getWardNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardName</column-name><column-value><![CDATA[");
		sb.append(getWardName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gpsPosition</column-name><column-value><![CDATA[");
		sb.append(getGpsPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telNo</column-name><column-value><![CDATA[");
		sb.append(getTelNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessNo</column-name><column-value><![CDATA[");
		sb.append(getBusinessNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessType</column-name><column-value><![CDATA[");
		sb.append(getBusinessType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registerAgent</column-name><column-value><![CDATA[");
		sb.append(getRegisterAgent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registerDate</column-name><column-value><![CDATA[");
		sb.append(getRegisterDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>representative</column-name><column-value><![CDATA[");
		sb.append(getRepresentative());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>representativeRole</column-name><column-value><![CDATA[");
		sb.append(getRepresentativeRole());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Business.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Business.class
		};
	private long _businessId;
	private long _userId;
	private String _userUuid;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private long _masterUserId;
	private String _masterUserUuid;
	private long _originalMasterUserId;
	private boolean _setOriginalMasterUserId;
	private String _name;
	private String _enName;
	private String _shortName;
	private String _address;
	private String _cityNo;
	private String _originalCityNo;
	private String _cityName;
	private String _districtNo;
	private String _originalDistrictNo;
	private String _districtName;
	private String _wardNo;
	private String _originalWardNo;
	private String _wardName;
	private String _gpsPosition;
	private String _telNo;
	private String _fax;
	private String _email;
	private String _businessNo;
	private String _businessType;
	private String _registerAgent;
	private String _originalRegisterAgent;
	private Date _registerDate;
	private String _representative;
	private String _representativeRole;
	private long _columnBitmask;
	private Business _escapedModel;
}